### ISSUE TITLE
Cardboard, GVR video plugin and 360-Video

### ISSUE THREAD

**Issue by DaRockJaeger** [googlevr/gvr-unity-sdk#1000]
Hello, I have a question:
In the official documentation, following statement can be read:
https://developers.google.com/vr/develop/unity/video-overview

> Note: This plugin supports Daydream only.

Does that mean that GVR video plugin only runs on DayDream?
I created a Cardboard-Application containing a 360 degree video and everythong seems to work fine.
I can't test it with a original cardboard, but on my Android phone, everything seems to work.

What do you mean with "This plugin supports Daydream only"?
What will be the effect for my cardboard app?

At first glance, I can't see any problems.

Best regards

**Comment by rusmaxham** [comment]
What this means is that the video plugin is only fully supported on Daydream-ready devices.  It does work on some other Android devices, but not all due to API or hardware incompatibility.  If you are targeting a wide range of devices that you may not be able to verify it works yourself, this may not be the best solution for your app.  If you are targeting a range of devices that you CAN directly verify and it works on all of them, then this may be a good solution for your app.
