### ISSUE TITLE
Why version of ExoPlayer is only 1.5.11?

### ISSUE THREAD

**Issue by KosmoGalaxy** [googlevr/gvr-unity-sdk#1037]
I get that introducing of ExoPlayer 2 would need a lot of rewriting of the support library. Though, 1.5.11 is not the latest version of ExoPlayer 1. Is it because of some stability issues or something or is it actually in the roadmap? Can I and/or should I update ExoPlayer 1 version on my own in my local copy of the SDK? And last question: Is the ExoPlayer support in the SDK going to receive updates in the future?

**Comment by rusmaxham** [comment]
It is due to a lack of ongoing maintenance on the component.  Since there haven't been any reported issues related to ExoPlayer, it hasn't received any maintenance.  If there is a specific issue you are having with GvrVideoPlayerTexture and/or ExoPlayer, please file an issue report with the specifics of the issue.

**Comment by rusmaxham** [comment]
You can try updating the build.gradle file to request a newer version of ExoPlayer, but we haven't done any testing to verify there aren't any issues with it.  There are no planned updates for GvrVideoPlayerTexture at this time.
