### ISSUE TITLE
Noisy distorted screen before entering a scene

### ISSUE THREAD

**Issue by foundway** [googlevr/gvr-unity-sdk#128]
I got this noisy distorted screen every time when I enter a scene on Galaxy S6 with Unity 5.3 and Cardboard SDK 0.5.2. Does anyone sees the same issue? Looks like the render buffer is not cleaned. Any though and workaround?

![screenshot_2015-12-19-04-14-46](https://cloud.githubusercontent.com/assets/1289089/11910091/b0bd2bbc-a5a4-11e5-8c92-718a444c3f0e.png)

**Comment by foundway** [comment]
I have found that stereoScreen.Create() in CardboardPreRender.cs is causing the issue:

  void OnPreCull() {
    Cardboard.SDK.UpdateState();
    if (Cardboard.SDK.ProfileChanged) {
      SetShaderGlobals();
    }
    camera.clearFlags = Cardboard.SDK.VRModeEnabled ?
        CameraClearFlags.SolidColor : CameraClearFlags.Nothing;
    var stereoScreen = Cardboard.SDK.StereoScreen;
    if (stereoScreen != null && !stereoScreen.IsCreated()) {
      stereoScreen.Create(); // <------ this line cause the issue. 
    }
  }
 
commenting out this line doesn't seems effect the basic rendering function though. Can anyone tell me if this is going to cause any problem?

**Comment by smdol** [comment]
It will not cause any problem (as long as you use the default Distortion Correction Method of "Unity").

**Comment by RichLloyd** [comment]
I also occasionally see similar with Galaxy S6 + Unity 5.3 + Cardboard SDK 0.5.2.

**Comment by smdol** [comment]
Does this happen for any scene?  We tried the demo scene with the same combination of hardware and software and did not see this result.  

Are you using any rendering features that are not in the demo scene?  (Light maps, image effects, etc.)

**Comment by smdol** [comment]
Just release v0.6 of the SDK.  I've never seen this issue before myself, so can you try to replicate using the new release?

**Comment by monizka** [comment]
I got same issue in my project with Unity 4.6.1 + Galaxy S6 + Cardboard SDK 0.6. It is working fine at editor, but it happens when apk plays in phone. Only way that I found to get rid of start noise is setting distortion correction in cardboard.cs as none, but it is not the solution as it disable the distortion for lens. Funny thing is that it is not occurring at all scene transition, just some of it.
p.s: I am using Application.LoadLevelAsync for scene transition.

**Comment by smdol** [comment]
Correct me if I'm wrong but so far everyone is seeing this only on Galaxy S6?

@monizka The problem appears to be pixel garbage in the distortion texture.  Makes sense you don't see it when distortion is set to None, since the distortion texture is not used in that case.

Can you try what @foundway did, removing the call to .Create() on the texture?  Does that fix it for you too?

**Comment by monizka** [comment]
I haven't tried on different device, so I can't guarantee that it is only happening on Galaxy S6. 
I tried to remove stereoScreen.Create() in prerender.cs, but that didn't make any change for me. Maybe I will try again for make sure.

**Comment by smdol** [comment]
There's another call to .Create over in Cardboard.cs, so make sure to remove that one too.

**Comment by monizka** [comment]
yeah that fixed it. Thanks for help!

**Comment by justinwasilenko** [comment]
Can confirm this is happening on the Samsung S6, but not on a Samsung S3.

**Comment by nathanmartz** [comment]
Thanks for the confirmation. We'll fix this officially in the next SDK update.

**Comment by foundway** [comment]
Any update for this issue? Removing both stereoScreen.Create() in CardboardPreRender.cs and Cardboard.cs resolves the issue but I wonder if we are getting an official patch?

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
