### ISSUE TITLE
Tracking is jittery in non VR mode

### ISSUE THREAD

**Issue by renardmf** [googlevr/gvr-unity-sdk#170]
I was trying to use the non VR mode of this SDK for 360 video but for some reason the tracking is very jittery. Is there any way to smooth this out or something else I should try to help remedy this?

Thanks in advance.

**Comment by smdol** [comment]
The tracking is a bit sensitive right now to hand jitter, which gets worse when you hold the phone away from your head.  For non VR, you could work around this with a bit of smoothing.  This would be done by modifying CardboardHead.cs to use Quaternion.Slerp() in the rotation update, with a multiple of Time.deltaTime as the interpolation factor.

Strong caution: don't be eager to apply in VR mode.  It increases perceived lag by a factor that depends on the user's phone performance (or lack of), which leads straight to nausea for an unknown percentage of your users.  Check if Cardboard.SDK.VRModeEnabled is false before using smoothing.

(We are still working on improving the overall tracking quality across all the phones in the market, with all the varying performance and gyro quality levels out there.  Not easy, unfortunately.)

**Comment by paulgailey** [comment]
for a video player app we mitigated this severe jitter at line 113 of GvrHead.cs with the addition of:

`if (!gvr.VRModeEnabled) {
					transform.localRotation = Quaternion.Slerp (transform.localRotation, rot, Time.deltaTime * 8);`

however we've since eventual noted horizon drift/tilt in the app. At this point it's unclear if it's directly related to the deltaTime or something else.

Do you think @smdol that drift could be an unintended consequence of that deltaTime? 

If not are there ways of mitigating gyro drift on a 0.9.1 build despite Auto Drift being now a feature of the NDK per the v0.8.1 Update ? (we also sensor reset a Samsung6 gyro to be double sure)

**Comment by PalashBansal96** [comment]
Hi, I was trying to find this head tracking in the non-VR mode in the current SDK, but it stops it on doing `XRSettings.LoadDeviceByName("");` Is there still a way?

**Comment by rusmaxham** [comment]
Go to [this document](https://docs.unity3d.com/560/Documentation/Manual/VRDevices-GoogleVR.html) and scroll down to **Magic Window mode** for instructions on how to get access to non-VR mode head tracking.
