### ISSUE TITLE
Vergence issue in 0.7.2

### ISSUE THREAD

**Issue by mark-steadman** [googlevr/gvr-unity-sdk#215]
I am trying to update a Unity project that previously used the Google Cardboard SDK version 0.5.2 to 0.7.2 (Unity version 5.3.4), but the output looks very strange in both the editor and through the viewer (using iPhone5 editor emulation and an iPhone5 device). This is what the demo scene looks like in the editor:

<img width="599" alt="screen shot 2016-05-04 at 13 25 50" src="https://cloud.githubusercontent.com/assets/15779053/15015976/c9996140-1206-11e6-9b74-9f1310b548a5.png">

In the viewer, you get double vision. The reticle, which is meant to be centred, appears to be much higher than centre and, in the Editor, close to the outer edges of the screen.

Adjusting the Stereo Multiplier (on the Stereo Controller) has little to no effect on this, but this wasn't an issue in 0.5.2.

**Comment by smdol** [comment]
Q: What viewer are you using?  In the Unity editor do you have it selected, and on the phone do you have the correct QR code scanned?  

The reticle is actually not supposed to be perfectly centered.  It is meant to be directly under your pupils (actually, center of the viewer lens), which for a tiny phone like iPhone 5 is closer to the upper/outer corners, especially if you have the default v2 Cardboard set as the viewer.  

The screenshot above looks kind of normal for this configuration, which is why I'm double-checking that you have the correct viewer configured -- a mismatch will cause double vision and warping.

**Comment by mark-steadman** [comment]
I'm using a Leap-HD viewer. Do you think this could be the issue?

I would am surprised if so, because when I use version 0.5.1 (not 0.5.2 as mentioned previously), the render looks very different - things centred in front of the cardboard head appear much closer to the centre. Also, changing the Stereo Multiplier on the StereoController has a noticable effect in 0.5.1. It's too strong when set at 1 and there is no stereoscopy when set to 0. This setting has next to no effect in 0.7.2.

I have Cardboard set to use v1 (2014).

**Comment by smdol** [comment]
The profile setting on the Cardboard component applies only to the emulation mode, when you play the game in Unity itself -- think of it as a "developer mode" setting.  To change the profile setting used on the phone, you have to scan the viewer's QR code from within your app while it is running on the phone, which you  initiate by tapping the gear icon.

**Comment by mark-steadman** [comment]
That's useful to know, thank you. However, regardless of the cardboard setting the reticle does not appear even close to centred when looked at through the viewer.

If I load the demo scene for 0.5.1 and 0.7.2 and use identical settings (setting the screen size to iPhone 5 and the viewer to v2) I get a dramatically different output. Changing the viewer setting has a comparatively subtle effect.

Here's the result produced by loading the demo scene in 0.5.1 and 0.7.2.

![cardboard_examples](https://cloud.githubusercontent.com/assets/15779053/15246750/28104f02-1907-11e6-926f-ab288672d0cf.png)

Firstly, in version 0.5.1 (left column) setting the stereo multiplier to zero results in the reticle being centred in both views. Increasing it moves them further apart, which is the behaviour I would expect. 

In 0.7.2, the reticle is much closer to the outer edges of the views and higher. Changing the stereo multiplier has a very small effect in the opposite direction. The output appears the same on the device.

Is it the the older version of the SDK was incorrect, and it just so happens that the resulting output worked with my viewer? I confess I find it difficult to imagine a situation where the two views produced by 0.7.2 could be resolved by the brain, but presumably this is designed to account for lens distortion in a way that is quite different to 0.5.1.

**Comment by smdol** [comment]
Quick notes:  After v0.6, changing parameters on the main camera (including stereoMultiplier) don't take effect immediately.  This is a performance optimization -- we were recomputing way too much stuff each frame.  You can force it, though, by turning on keepStereoUpdated.

In your 2nd set of screenshots, the vignette in 0.5.1 looks like a V1 Cardboard but the one in v0.7.2 looks like V2 Cardboard.  Those are the respective defaults for those versions of the library.  You can control that in the editor on the Cardboard's editor panel.  On the phone, scan the QR code to make sure you have it set as desired.

**Comment by sign00** [comment]
I have been browsing through the code and tweaking parameters for a while now and have the same issue. In the Editor, when simulation is playing, keepStereoUpdated does not seem to have any effect on the views nor does the Update Stereo Cameras button. Interestingly, vergence is somewhat correct for 2 predefined profiles: Galaxy Note S4 and LG G3, regardless of the device type (Cardboard June 2014 / May 2015 or Google Tech C1). 
I am trying to solve the issue within the Editor prior to solving it with both actual device and Cardboard viewer, because they present the same behavior (lack of stereopsis) besides the fact that the actual device screen size is wrongly detected, hence adding more problems.... 
Apps downloaded for Cardboard in the Store react the same (not usable so uninstalled, and from their respective comment section other people have the same issue). 
Oddly, one app (not for Cardboard) works well in VR so there seems to be no issue with the device and Cardboard viewer. 
It would be very helpful to actually get the Stereo Controller to work - so this is not a bug (hopefully) ? Gonna try my luck with StackOverflow in case I am missing something...
Of course, I used the QR code and as mentioned the Cardboard viewer works but not with Cardboard apps, i.e. not with Unity built samples nor downloaded Cardboard apps.
