### ISSUE TITLE
GVRAudioRenderer and GVRAudioSource sidestep entire mixer workflow in Unity

### ISSUE THREAD

**Issue by jonhillman** [googlevr/gvr-unity-sdk#241]
I feel like I must be missing something, but haven't found a way to use Unity 5's mixer workflow with GVR audio spatialization (spatializer, renderer, and custom source). There is no way to setup a mix so that sources are routed to groups, or to individual mixers. Is this the intended long term approach? Cutting out that workflow is basically throwing out the main advancement Unity 5 brought to audio workflow.

**Comment by jonhillman** [comment]
I guess what I should ask is how far out is a Native Audio Spatializer (introduced in Unity 5.2) implementation that doesn't require custom source components? Simply using the stock AudioSource component and mixer workflow is much more desirable.

**Comment by anokta** [comment]
@jonhillman

**Comment by anokta** [comment]
@jonhillman Thanks for the feedback! The current version of the SDK does not support mixer routing per source due to our internal audio bus architecture. However, we are aware that is a fairly useful workflow to have and we are in fact working directly with Unity to provide such a solution as soon as possible.

**Comment by jonhillman** [comment]
That's great – I figured that'd be the case after thinking about it a bit
more. It looks like all of the solutions are moving to the Native Audio
Spatialization model, and the workflow is great for the ones I've tried
that do.

You don't happen to know a rough timeline (weeks, months?), do you? I'd be
happy to help develop/test such a solution.

On Tue, Jun 7, 2016 at 7:17 PM, Alper Gungormusler <notifications@github.com

**Comment by CodingJar** [comment]
I'm reviving this thread because I just spent an entire day trying to debug what's going on with the GoogleVR Audio Spatializer in the latest build.  I'm inserting code before GvrAudioSource gets a chance to play the audio in order to switch the MixerGroup to another one.  Sometimes this works and sometimes it doesn't.  About 50% of the time I lose the spatialization (i.e. rotating my head doesn't rotate the sounds around me -- it's like my head is always facing forward).  I can't reproduce it on a smaller project, it only appears to happen in my complex project.

Is this still a known issue?  If it is, can we get a warning in the code when it detects it's not playing on the Master group?
