### ISSUE TITLE
"No GvrViewer instance found" when GvrController is active from the start

### ISSUE THREAD

**Issue by vitorbalbio** [googlevr/gvr-unity-sdk#246]
Hi!
The GvrViwer is working and i don't see any problem in it behavior but I'm getting this error on the console at the start, and only if the Gvr Controller is active from the start too. If it's activated latter i don't get any error message:

> "No GvrViewer instance found.  Ensure one exists in the scene, or call GvrViewer.Create() at startup to generate one. If one does exist but hasn't called Awake() yet, then this error is due to order-of-initialization.In that case, consider moving your first reference to GvrViewer.Instance to a later point in time. If exiting the scene, this indicates that the GvrViewer object has already been destroyed."

I tried to setup the GvrViwer and the GvrController in the script execution order but it don't seam to fix it as the report suggest.

A simple workaround is set the GvrController disabled by default and start it with other script during the execution. But i don't think that is designed to be that way right?

**Comment by smdol** [comment]
This happens because the controller does a Recenter operation in Awake(), and at that moment the GvrViewer object may not have been instantiated yet.  The GvrViewer.Instance property returns null, and GvrController handles that properly, but it still does cause this error message as a side effect.  It's harmless for you, and we will fix it in the SDK so it is not alarming.

**Comment by vitorbalbio** [comment]
Thanks smdol ;)
