### ISSUE TITLE
How to use stream audio for GvrAudioSoundField?

### ISSUE THREAD

**Issue by xdf103** [googlevr/gvr-unity-sdk#260]
We are building a VR video player using gvr-unity-sdk. Audio comes from a video stream. How can we play the audio using a GvrAudioSoundField (version 0.8.5)?

**Comment by anokta** [comment]
The audio is required to be in a form of two stereo Unity AudioClips (WY & ZX channels of the first-order ambisonics file respectively). So, there is no direct support to playback audio from the video stream as it is atm (v0.8.5). This is due to the limitation of multi-channel audio support in Unity's underlying audio processing pipeline.

**Comment by xdf103** [comment]
We can handle the steaming and reading the audio data. Is there anyway to feed the audio data (not audioclip) to GvrAudioSoundField directly?

**Comment by nathanmartz** [comment]
If you stream using Unity's WWW class you can request the results as an audioclip, which will work with our plugin.

**Comment by xdf103** [comment]
Thank you!
