### ISSUE TITLE
0.85 - UI layer settings are gone? - how to hide gear icon / alignment marker

### ISSUE THREAD

**Issue by noemis84** [googlevr/gvr-unity-sdk#266]
1. In 0.85 there seem to be no ui layer settings in GvrViewer... but why? And how can I disable gear icon and alignment marker now...

![ui_layer_settings](https://cloud.githubusercontent.com/assets/13518143/16837716/4b560b48-49c5-11e6-84a8-5a825284d254.jpg)
1. Another strange thing is: AddStereoControllerToCameras() on same script at Start(). Why? When using the GvrMain prefab and instance it when I need it... it first makes my orthographic UICam to a stereo cam... completly sensless for me.
2. is NFC permission in the manifest for android important, or can remove it?

**Comment by noemis84** [comment]
The answer to my question 3 seems to be: Yes. It's important. Removing NFC permission from manifest causes a crash on my S6 when going to home screen during runtime...

**Comment by arturleao** [comment]
This is now done in the GvrPostRender.cs in the DrawUILayer. Its not exposed in the GvrViewer anymore like you mentioned and the method for drawing it, just assumes a bunch of stuff, should be easy to fix.

Here's whats currently happening:
 private void DrawUILayer() {
    bool vrMode = GvrViewer.Instance.VRModeEnabled;
    if (Application.isEditor) {
      ComputeUIMatrix();
    }
    uiMaterial.SetPass(0);
    DrawSettingsButton();
    DrawAlignmentMarker();
    if (vrMode) {
      DrawVRBackButton();
    }
  }

**Comment by noemis84** [comment]
@arturleao thank you for your answer, but sadly it's not that simple... I already tried it and a minute ago again to make sure we talk about the same. The UI is gone in editor, but not on android. The reason is probably in here:

`void OnRenderObject() {
    [.....]

    if (!GvrViewer.Instance.NativeUILayerSupported) {
      DrawUILayer();
    }
  }`

It seems, that DrawUILayer() is only called for devices/platforms(?), which have no NativeUILayerSupport... but obviously my S6 (and I asume many more or even all) still show the UI...

**Comment by arturleao** [comment]
Yes, you are right, I was messing with the code and couldn't properly show/hide stuff, looks that the changes go deeper than this.

**Comment by miraleung** [comment]
Thanks for the feedback! Responses below:

_UILayer settings._ Our latest Java SDK ensures that those three UI elements will always be drawn in stereo mode. However, we'd love to understand your use case, and it would be great if you could elaborate.

_AddStereoControllerToCameras() on Start()._ Dual cameras will no longer be needed in the upcoming native Unity integration. In that version, we will still get both eyes rendered from a single camera when compiling with VR support. One of our goals with the 0.8.5 SDK is to gradually migrate the API surface towards the native integration SDK. GvrMain is among the prefabs that will no longer be needed in that future SDK, so we're deprecating it to begin with.

Hope this helps!

**Comment by ezonecom** [comment]
Having a single camera sounds great. However, will it still be possible to target separate left and right eyes, for example to render a stereo cubemap video?

Simon Edis


On 15 Jul 2016, at 6:54 AM, Mira Leung <notifications@github.com> wrote:

Thanks for the feedback! Responses below:

UILayer settings. Our latest Java SDK ensures that those three UI elements will always be drawn in stereo mode. However, we'd love to understand your use case, and it would be great if you could elaborate.

AddStereoControllerToCameras() on Start(). Dual cameras will no longer be needed in the upcoming native Unity integration. In that version, we will still get both eyes rendered from a single camera when compiling with VR support. One of our goals with the 0.8.5 SDK is to gradually migrate the API surface towards the native integration SDK. GvrMain is among the prefabs that will no longer be needed in that future SDK, so we're deprecating it to begin with.

Hope this helps!

**Comment by noemis84** [comment]
thank you @miraleung for your response. first I thing it's never a good idea not to let the developer decide if he needs such overlays or not, not even in a hidden option. our use case: we want to upgrade the settings behind the gear button... not just the cardboard settings dialog, but also give more options: distortion on/off (for performance reasons) and also enable or disable vr mode, because we also have a 360 single cam option to share experience or just make screenshots. see an example from us here: [OpenMovieVR](https://goo.gl/uecxrb) which is a remake from a well downloaded/liked older version: [OpenMovieVR_OLD](https://goo.gl/cgsx5A).

Also the alignment marker is not our favorite... just too bright (in some cardboards/devices annoying visible) and not fundamental necessary, because the alignment works well with gear button itself.

what @ezonecom said is also important for us. the option I used before is to set Toggle Culling Mask on the left/right cam in the prefab... I think in the future we have to set them via code after they are automatically created?

**Comment by MiCkSoftware** [comment]
+1 for UI overlay. If it becomes mandatory it should use a way darker color.

+1 for 3d switch but it seems we will have to deploy 2 builds... 😐

Cheers!

**Comment by miraleung** [comment]
Thank you very much for your feedback! 

_UI overlay._ We made this mandatory because we've seen too many people unable to perform basic functions like alignment, pairing, and exiting VR. The darker color is a great point, and we may look into this more.

_Distortion._ Turning off distortion makes for a suboptimal experience, so we intentionally don't support it as a pattern. Please consider implementing VS distortion, which is very fast and can work on hardware back to an S3. 

_Targeting left and right eyes._ Please see [this post](https://github.com/googlevr/gvr-unity-sdk/issues/263) on how it can be done in the native integration.

_3D toggling._ This can be done in the app - the TreasureHunt example shows one way of doing it. We can also toggle between 2D and 3D activities by importing a Unity project into Android Studio and making the switch programatically. 

Hope this answers your questions. Please feel free to make separate posts per issue moving forward, and again, we really value your feedback. :)

**Comment by MiCkSoftware** [comment]
Thanks for your feedback too!
I'll be glad if the overlay is darker so that it doesn't reflect on lenses
during dark scenes.

I am aware about the switch. I already implemented it in my game but I feel
like it won't be possible anymore with the release of native unity support.
Am I wrong?

Cheers!
Mick.

**Comment by miraleung** [comment]
No worries, the switch will still be possible in the native integration. :)

**Comment by noemis84** [comment]
_UI overlay._ Making visible elements in a SDK mandatory is in my eyes not good. I create cardboard apps over one year now... at the end, I never had the alignment marker and no user ever complained about it.

_Distortion._ Can you please specify "VS distortion". I never heard of it.

Thank you for the hint for Targeting left and right eyes and 3D toggling. I'll look at it, when I give >=0.85 a try. For now I'm back to good old 0.8 ;)

**Comment by smdol** [comment]
The UI layer is effectively migrating out of the SDK into the core VR support of Android N.  The approach is now to consider it part of the system UI, similar to the status bar and nav bar.  Thus apps have less ability to control its specific appearance, other than hiding/showing it as a whole.  Darkening the vertical bar (or something like that) is being looked at actively. 

VS distortion is discussed here: http://www.gamasutra.com/blogs/BrianKehrer/20160125/264161/VR_Distortion_Correction_using_Vertex_Displacement.php
Brian also gave a talk at I/O this year about it but I don't have the YouTube link handy.  It's used in Cardboard Design Lab and the Cardboard app's arctic-themed welcome scene.

**Comment by noemis84** [comment]
thank you @smdol for the link about VS distortion... sounds interesting.

"_3D toggling_. This can be done in the app"  - the TreasureHunt example"... what and where is it... in my sdk there is non such example.

I tried _"Expeditions"_ - first of all, it's not really working on S6 and S7 which is unbelievable... really? These most selled high end phones are not being tested?

But asuming  it uses newest SDK and we can take it as example. There I can see the fullscreen switch...
![screenshot_20160721-120831](https://cloud.githubusercontent.com/assets/13518143/17019632/9202056a-4f3d-11e6-9870-9d8c3f845cd8.jpg)

And I also can see it in VR in bottom right corner of right eye. Hey! Pressing it enables the one eye mode with a jerky gyro + touch overlay (where you can also change horizon), which makes it in my eyes **unusable**.

### I just dont't understand how can someone decide making things mandatory before it's usable... sorry! I'm very disapointed about constantly changing things which worked before.

I had my own gear icon, with a menue, which gives the user really OPTIONS. 

![screenshot_20160721-121121](https://cloud.githubusercontent.com/assets/13518143/17019770/58409fc0-4f3e-11e6-970d-31530890e73e.jpg)

You show some standard profils... ok, cool, this feature I was asking months ago ;( - but if you really want to make this gear icon settings menu a value, than PLEASE...

- integrate this VR switch
- using gyro as option
- touchmode

![screenshot_20160721-120840](https://cloud.githubusercontent.com/assets/13518143/17019953/5330e0b6-4f3f-11e6-8e24-87dd9ff16f2b.jpg)

### I really don't get it, why I have to write all these things... just let developer their options.

**Comment by arturleao** [comment]
I have a simple question, on iOS, in 360 mode, how do I get back? I cant show the back button and iOS does not have a back button embeded in the system like Android.

**Comment by youlweb** [comment]
+100% on getting back the ability to toggle the vertical bar+gear icon. 
In the app I'm building, I chose to display these options on the home screen only, then hide them during gameplay, which prevents annoying reflections in the lenses.
The risk that the toggling feature is even noticed by cardboard developers is minimal, considering the horrendous quality of most cardboard apps. They are less than optimized, to say the least.
However, for the few mindful and/or corporate developers out there, this option adds a much needed uptick in overall user experience quality, which is much needed in this fragile ecosystem.

**Comment by nathanmartz** [comment]
Hi, youlweb. Thanks for the feedback. Although we don't plan to make the core UX optional, we do want to solve the problems you were having. Regarding reflections from the divider and the gear, we're looking at a design update that should help a lot. I'm curious, what viewer were you using that had the most trouble with the divider?

Hiding some items once the user has been in VR for a while is also an interesting idea, esp for the divider. It's something we'll discuss more internally.

Please continue to highlight issues that you run into. We can't guarantee that we'll always make the exact changes you ask for, but understanding the challenges and asks from real world devs is super important to us.

**Comment by youlweb** [comment]
Hi Nathan, I'm using the Blitzwolf viewer. The lenses are surprisingly good, and will catch reflections whenever the app background is dark/black.
I must add that by far the most disrupting part of the UI is the back arrow in the top left corner, because it is drawn on useful screen estate, unlike the divider/gear sprites, that may be partly hidden by the viewer's eye divider (although it may cause reflections). Additionally, the back arrow is rendered on the left eye screen only, causing an unpleasant non-3D perception of that part of the scene.
I'm glad that various solutions are being explored to improve the user experience with GVR/Cardboard, an otherwise affordable and exciting VR landscape, which could gain mass adoption with the right level of quality built in its applications/games. I have reached 60+ FPS on a Galaxy S4 in the game I'm building, with engaging graphics, which now delivers a similar feeling as some of the more expensive experiences such as PSVR, on hardware that's already in the pocket of most consumers.
Thank you for your quick response, and encouraging words.

**Comment by justinISOFORM** [comment]
I have a client that is specifically asking for the back arrow to be removed from their app. Removing this as an option for developers does not seem like a good idea. Please put it back.

**Comment by CenekStrichel** [comment]
Is there any solution? I have exactly same problem as justinISOFORM, my client want to remove back button.  Any hack how can I do it?

**Comment by Rubinhuang9239** [comment]
Making gear and back mandatory is a really bad idea, it conflict with my UI and it just looks terrible.
Dose anyone how can i remove them anyway???

**Comment by blumersolutions** [comment]
+1 on having the option to remove the back button.

**Comment by prasetion** [comment]
hey, actually agree with @noemis84. Because in our previous app, we remove that UI.

I want to ask, my question:
i use unity 5.6 and gvr-unity-sdk 1.4.0, i have checked vr supported in player setting, and chose Cardboard SDK. i use vrsetting.enable = false in first scene ( in void Awake), but the UI that we talking about is called and showing at the first, when i try on my phone, so how to hide it at the first? is it an issue? or i miss something to check? thank you

**Comment by miraleung** [comment]
The first VR SDK in the list in Player Settings is loaded, so putting "None" before Cardboard should do it. There are further examples of how to switch between VR devices in Assets/GoogleVR/Demos/Scripts/DemoInputManager.cs
