### ISSUE TITLE
Floor Canvas dont shou 

### ISSUE THREAD

**Issue by gokooko** [googlevr/gvr-unity-sdk#275]
When i open Googlevr demo scene in Play mode i don't see the floor canvas, the cursor show that is dear bat it is not seen, when i change distortion correction   from Unity to None it is show.

![03](https://cloud.githubusercontent.com/assets/14280671/17083003/9fa7bc5e-5191-11e6-9649-a9d3ecc6d24b.jpg)
![01](https://cloud.githubusercontent.com/assets/14280671/17083002/9fa72a50-5191-11e6-92ad-731dc472d9c5.jpg)
![02](https://cloud.githubusercontent.com/assets/14280671/17083001/9fa57e80-5191-11e6-9146-1701912ee63c.jpg)

**Comment by Selzier** [comment]
Starting with 5.3.4p2, a bug in Unity prevents rendering World Space uGUI Canvases into a RenderTexture. Since RenderTextures are used for distortion correction, this effects all such canvases in VR. https://developers.google.com/vr/unity/release-notes#known_issues

Try installing Unity 5.3.4f1 or waiting for 5.3.6.

**Comment by nathanmartz** [comment]
Thats's correct. This is a confirmed unity bug.

**Comment by ashleydb** [comment]
5.3.6 just came out and I confirmed canvas objects were drawing again
earlier today.



Ashley Bennett
www.HiAsh.com
