### ISSUE TITLE
Settings Button Not Visible on iOS

### ISSUE THREAD

**Issue by dill0wn** [googlevr/gvr-unity-sdk#286]
OK, this might be outside the scope of this issue tracker, but I'm not sure where else to go and I was hoping somebody here might be able to point me in the right direction.  I'm using GoogleVR 0.8 in conjunction with Vuforia's 5.5.9 AR library.

When using GoogleVR by itself, the Settings button appears as normal.  However, as soon as I add Vuforia to the project I can't see the settings icon.

Has anyone encountered something like this before or have any advice?

EDIT: Here's some additional settings / version info
Mac OS 10.11.5
Unity 5.3.4f1
GoogleVR 0.8
Vuforia 5.5.9
XCode 7.3.1
iOS Deployment Target: 8.0, 9.3
Graphics API: OpenGLES 2

**Comment by smdol** [comment]
Vuforia is one of the other Unity SDKs or there that suits things like mess with the apps view hierarchy (or on Android it wants to provide the Activity class, like ours).  This does make it hard to mix them.  

In the iOS case, both SDKs may be trying to override the app controller to control how the view hierarchy is built.  The files that do that in our SDK are in Assets/Plugins/iOS - look for the two ObjC source files.  If Vuforia has similar files, then they may have to be stitched together.

Another possibility we will have to look at internally is if our code that turns on the UI elements makes an assumption about the view hierarchy that isn't true if Vuforia has modified it.

**Comment by dill0wn** [comment]
Thanks!

I missed a step in vuforia's integration documentation:
https://developer.vuforia.com/library/articles/Solution/Integrating-Cardboard-to-the-ARVR-Sample
There's a file, VuforiaNativeRendererController.mm, which you're supposed to delete if you're using Cardboard (GoogleVR), and it sounds like that file is the sort of thing you're talking about.

I Deleted that file, and voila! Thanks!

**Comment by nosmirck** [comment]
Hi, I'm finding a similar problem, I just didn't want to create a new issue since other people getting the same problem can find a solution here.

The VR UI (back button, settings button and alignment mark) is not showing on iOS.

I don't have Vuforia in my project, but I have AppsFlyer and I checked and it has a couple of ObjC code inside Plugins/iOS/ folder.

It's an AppController like CardboardAppController and I think this one is interfering with Cardboard's UI.

I know I have to mix both of them, but I don't have experience with this and I have no clue how to do it.

Can anyone help me with this?

Both files can be found here:

AppsFlyer: http://pastebin.com/YCaiGYzp
Cardboard: http://pastebin.com/3XCd5pxQ 

Thanks in advance.
