### ISSUE TITLE
frame rate low and jumping in daydream project Unity3D

### ISSUE THREAD

**Issue by overfile** [googlevr/gvr-unity-sdk#302]
Hi, 
Recently i start to migrate my project to google daydream and when i try to run in Nexus 6p ("The Nexus 6P is the only phone supported as a headset phone for a Daydream development kit at this time"  say google in https://developers.google.com/vr/concepts/dev-kit-setup) the frame rate are jumping between 45fps - 60fps, this is very unconfortable to final user.

I read the documentation to unity and i can't improve the frame rate, i think don't use the correct setting because i don't specific in any sites i develop to daydream and not to cardboard vr.

Any idea to help me?

thanks :)

**Comment by jamesvecore** [comment]
We are seeing the same stutter, especially when the player turn's his or her head.

**Comment by overfile** [comment]
Maybe... i tried to change parameters in gvr viewer and Pre/Post render cameras but is not enough to create a stable frame rate in Nexus 6P. 

What's can i try?

I hope Unity3D will support to Vulkan Api and this improve a Google vr projects.

**Comment by nathanmartz** [comment]
The public version of Unity doesn't currently include native support for Daydream. Until that is released, you won't get many of the features required for smooth, low latency VR even on a 6P. We'll hopefully have more to share about native Daydream support in Unity soon.

**Comment by overfile** [comment]
I tried with GVR 1.0 and Unity Daydream Preview but the framerate is not correct.

I was optimized my scene and now i have 60fps but jummping to 40fps-45fps.

I tested in a Nexus 6p, and i have a issues... for example i have a issue with Daydream Controller because when in my Nexus 6p is correct sync by bluetooth with other device, the game only works in 45fps (jumping to less) and in the left eye generate flickers and a retard refresh image, the right eye works more good bu, i think is strange... If i deactivate the bluetooth, the game works in 60fps but jumping as the older SDK version.

I think the controller is not optimized or in my project the controller is broken... Can i help me please?

Thanks.

**Comment by nathanmartz** [comment]
You're talking about several issues all at once:

Regarding framerate overall, did you follow [these steps](https://blogs.unity3d.com/2016/09/22/daydream-technical-preview-available-now/) when configuring your project? If not, you can be running without the correct clock speeds and will run very fast for a short period of time and then will slow down.

The framerate drops w/ controller emulator on 6P are a known issue. You shouldn't see them with real hardware.

The flickering in the left eye may be fixed in our next update. If you can post a video of the screen here that would help.
