### ISSUE TITLE
Adding gvrAudioRoom causes Unity 5.3.3f1 to Crash

### ISSUE THREAD

**Issue by fredlemieux** [googlevr/gvr-unity-sdk#342]
If you try to add gvrAudioRoom into a unity3D project Unity Crashes. 

To reproduce the error use the gvr-unity-sdk headset demo scene, press play and all works well.

Add the grvAudioRoom prefab and then press play and Unity crashes without warning.  Is anyone else having this issue?

**Comment by anokta** [comment]
Hey Frederique,

Could you confirm which SDK version and platform that you encountered the issue? We recently found a bug in v1.0 (d5141218a3a101dc2cc73c92a90ff4172e7b1c75) which causes an immediate crash on Windows when there is a GvrAudioRoom in the scene. The issue should be fixed by the latest v1.0.1 update (5d75c2a4b04960e6ffc9728e4c5e8ec48406b296). Please let me know if it works out for you.

Cheers

**Comment by fredlemieux** [comment]
I've updated to the latest sdk version 1.0.1 and it all works fine.  thanks!

**Comment by nathanmartz** [comment]
Great!
