### ISSUE TITLE
GvrAudioSoundfield not documented well enough

### ISSUE THREAD

**Issue by jurrienowl** [googlevr/gvr-unity-sdk#367]
Hello everyone,

I am working on a mobile VR application that uses spatial audio for a 360 video. I am using the GVRAudioSoundfield with Ambix files. When I use the Youtube spatial audio specefication and assign the correct audio channels(WYZX) the audio is totally off. GvrAudioSoundfield is not documented well enough in the scripting reference to resolve this issue on my own. Does anyone have an idea about what I could be doing wrong?

**Comment by handyface** [comment]
I also have problems getting GVRSoundfield to work. I have [this](https://drive.google.com/open?id=0B5XLOVf_JxT4Ni1KM2FyTjlZYlk) ambisonic audio file cut with Audacity to 2 files. The first and second channel to one Wav, and the third and fourth to the second to another Wav. When I connect these files to the SoundField component, set to (0,0,0), the audio directions still seem off.

I keep wondering if I am doing something wrong, or is the GVR implementation off?

**Comment by jkammerl** [comment]
Thanks for you bug reports. We'll take a closer look at your sound file. Could you share which Unity version you are using? 
1) We recently discovered a bug in Unity that affects sound field rendering when there is a translation between the camera position and the sound field center. It should be fixed in the upcoming Unity release and they are considering back porting the fix to earlier versions too.

**Comment by handyface** [comment]
Thanks for your response. I use 5.4.1p4



On Mon, Nov 7, 2016 at 6:46 PM +0100, "Julius Kammerl" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for you bug reports. We'll take a closer look at your sound file. Could you share which Unity version you are using?
1) We recently discovered a bug in Unity that affects sound field rendering when there is a translation between the camera position and the sound field center. It should be fixed in the upcoming Unity release and they are considering back porting the fix to earlier versions too.

-

**Comment by handyface** [comment]
Do you have a unity issue link to the problem you are describing? I'd like to follow and inspect the issue progress.
