### ISSUE TITLE
Audio error after upgrade.

### ISSUE THREAD

**Issue by justinwasilenko** [googlevr/gvr-unity-sdk#396]
I just upgraded our project from 0.8.5 after reports of the S7 having double vision (again)...

We upgraded 1.10 and Unity 5.4.3 (Not the Technical preview because of iOS support) and after the upgrade and following the upgrade instructions when I play the same I get this error multiple times from every GVRAudioSource:

EntryPointNotFoundException: SetSourceListenerDirectivity
GvrAudio.UpdateAudioSource (Int32 id, .GvrAudioSource source, Single currentOcclusion) (at Assets/GoogleVR/Scripts/Audio/GvrAudio.cs:160)
GvrAudioSource.Update () (at Assets/GoogleVR/Scripts/Audio/GvrAudioSource.cs:328)

Gvr Audio Spatializer is set correctly any ideas?

**Comment by anokta** [comment]
Hey Justin,

Sounds like there was a problem importing the audio libraries (*audioplugingvrunity* files in the Plugins folder) in your project. Could you verify if you can reproduce the issue importing the SDK in a new Unity project? Otherwise, the easiest thing you could try would be to try and replace the Plugins folder manually into your project. 

Could you also give some more information on which platform do you experience the issue in case there's something else going on? Is it happening only in the Editor, or also in S7?

Cheers

**Comment by justinwasilenko** [comment]
Yep that was the problem. Deleted the Plugins folder when the project wasn't opened, and then reopened and re-imported the GVR asset package. Error messages went away.

**Comment by vivekghanchi** [comment]
EntryPointNotFoundException: CreateSoundObject
