### ISSUE TITLE
What is the correct way to add a HUD?

### ISSUE THREAD

**Issue by lexar** [googlevr/gvr-unity-sdk#410]
Hello,

the [docs](https://developers.google.com/vr/unity/plugin) say:
"Elements under a Head node will maintain a fixed position on screen, thus acting like a Heads-up Display (HUD)."
But they also say:
"Deprecated Prefabs: GvrHead"

Using Unity, I am trying to attach a UI Image inside a Canvas as a HUD like this:
`myCanvas.transform.SetParent(GvrViewer.Controller.Head.transform, true);`

I can see the image and it remains fixed on both eyes, but I find it very difficult to put the image at the right position. I am unsure how to change the several transforms involved. The outcome appears to be almost random.
So is adding a UI Image like this the correct way to do this? If yes, is it the best? And where can I read about how to position that element, preferrably within Unity's editor?

If this is the wrong place to ask, please point me to the right one - that's another difficult thing for me to find out :)

Thanks, l

**Comment by Selzier** [comment]
Now, you would set the UI objects as a child of Main Camera. If you want to do this at runtime, myCanvas.transform.SetParent(Camera.Main.transform, true); would also work.

Create a worldspace ui as seen in this video: 
https://www.youtube.com/watch?v=x0CAZYvrzGM

It would be better to set the position in the unity editor (not in script) by moving the transform in the Scene window and viewing what it looks like in the Game window. 
(You can do this at runtime, but you must "copy component" before you stop playing and then "paste component values" once play mode has stopped.)

Because you want the UI in front of the camera, it's position as a child of the camera will be somewhere around (0,0,1).

So this is very easy. Make UI as seen in video. Put Canvas as child of Main Camera. Position in Editor Window, view correct position in Game window. Now press play and UI is ready.

**Comment by lexar** [comment]
Sorry for the late reply, I thought I already did. Thank you very much for the detailed answer, got a HUD now!
