### ISSUE TITLE
ShutdownSoundfield() should call GvrAudio.DestroyAudioSoundfield() in GvrAudioSoundfiled.cs

### ISSUE THREAD

**Issue by StevenKeXu** [googlevr/gvr-unity-sdk#434]
As the title texted above, is this a wrong in Daydream 1.10 for Unity?
// Shuts down the source.
  private void ShutdownSoundfield () {
    if (id >= 0) {
      for (int channelSet = 0; channelSet < audioSources.Length; ++channelSet) {
        ShutdownChannelSet(audioSources[channelSet], channelSet);
      }
      GvrAudio.DestroyAudioSource(id);
      id = -1;
    }
  }

**Comment by anokta** [comment]
Hey Steven,

Thanks for spotting this! Indeed, this looks like a typo, should be _GvrAudio.DestroyAudioSoundfield(id)_. Will be fixed in the next update.

Though, please note that, this should not affect the functionality of the component, i.e., it is a cosmetic typo only, where both methods functionally behave identically under the hood.
