### ISSUE TITLE
Some image effects wont work

### ISSUE THREAD

**Issue by Oaken3d** [googlevr/gvr-unity-sdk#448]
Some image effects wont work, one is Screen Space Ambient Occlusion and the other one is Global Fog, i add it to PostRender but still not working

**Comment by synthercat** [comment]
Have you tried to disable direct render on the stereo controller? If that fails try to press update cameras to create right and left camera and place the effects there. You will have performance issues though

**Comment by Oaken3d** [comment]
It seems that there is no more direct rendering in the latest version, I'm using 1.1 and I don't  see it. I try to put effects on every camera too, but in the editor it seems like everything works, but once exported to Android i don't see any effect.

**Comment by miraleung** [comment]
Which Unity version are you using, and which platform (Cardboard or Daydream) are you developing for? Could you please clarify what you meant by image effects not working?

For the technical preview (GVR13), it's a known issue that post processing effects will result in artifacts.

**Comment by dspmania** [comment]
Same here. I'm using 'google vr sdk for unity 1.1' with unity technical preview (5.4.2f2-GVR13).
As gvr legacy scripts' (StereoController.cs, GvrEye.cs, etc) bodies are removed by the compiler derivate #if !UNITY_HAS_GOOGLEVR || UNITY_EDITOR when deployed on actual device, bloom effect attached to Main Camera Left, Main Camera Right (which are exposed by attaching StereoController.cs to Main Camera in unity editor) does not work.

Is there any way to use unity's built-in image effects on google vr sdk 1.1 and gvr 13?

**Comment by quentinleguennec** [comment]
@dspmania Using SDK 1.1 and GVR 13 I got the effect working on the device by moving my camera effect script to the main camera GameObject (and not the "Left Camera" and "Right Camera" GameObjects). This will not display the effect in Unity emulator though, if you want to have both the effect on the emulator and device then you will have to use some "#if UNITY_EDITOR" to add the script to "Left Camera" and "Right Camera" at runtime (and still keep the script on the main camera for the device).
This is because "Left Camera" and "Right Camera" are only created when running the app from Unity emulator, and not when the app is installed on a device. I didn't had to disable "direct render" (doesn't seem to exist anymore ayway).
