### ISSUE TITLE
 EntryPointNotFoundException: SetListenerTransform

### ISSUE THREAD

**Issue by AayushU** [googlevr/gvr-unity-sdk#462]
Hi,

I am trying to play a video using GVR SDK 1.2.0 and I'm getting these errors in the logs: 

`02-09 17:37:06.023 21539 21556 I Unity   : EntryPointNotFoundException: SetListenerTransform
02-09 17:37:06.023 21539 21556 I Unity   :   at (wrapper managed-to-native) GvrAudio:SetListenerTransform (single,single,single,single,single,single,single)
02-09 17:37:06.023 21539 21556 I Unity   :   at GvrAudio.UpdateAudioListener (Single globalGainDb, LayerMask occlusionMask, Single worldScale) [0x00000] in <filename unknown>:0 
02-09 17:37:06.023 21539 21556 I Unity   :   at GvrAudioListener.OnEnable () [0x00000] in <filename unknown>:0 
02-09 17:37:06.023 21539 21556 I Unity   :  `

It looks like the audioplugingvrunity.dll/.bundle from the default game might be missing this function? Has anyone seen this issue already?

**Comment by anokta** [comment]
Hey,

I believe this happened when updating the GVR SDK in an existing project? Replacing the package while Unity Editor is open can cause this type of issues, due to the fact that Unity fails to remove the audio plugin libraries running in the background (in the Plugins folder) - without giving any errors. Could you try:
1. Close Unity Editor
2. Remove the GVR SDK assets from your project folder directly using file explorer (note that, removing the Plugins folder should technically be enough in case you're worried of losing modified changes etc. in your project). 
3. Open Unity Editor & re-import the GVR SDK 1.20 Unity package.

Hope it addresses the issue!

**Comment by AayushU** [comment]
Thanks that was it. I removed the old files and reimported and it worked fine!
