### ISSUE TITLE
Unable to run Unity builds on a Google Pixel XL.

### ISSUE THREAD

**Issue by kaleknavicius** [googlevr/gvr-unity-sdk#463]
Hi there,

I'm super new to this so bear with me. I'm trying to learn to develop VR for Pixel XL using Unity 5.5.1f1 and GVR Unity SDK 1.2. I was following Udacity's VR course, as well as watching some tutorials, and also tried to play with settings myself, however I always get the same error when trying to Build & Run:

<img width="637" alt="screen shot 2017-02-11 at 19 54 43" src="https://cloud.githubusercontent.com/assets/13118710/22856119/f75a35ca-f093-11e6-9fa4-5dc9619b0a01.png">

I only want to build cardboard apps for now, so Daydream is not needed. I also tried disabling NFC on my phone as explained here: https://www.vrheads.com/how-play-google-cardboard-games-using-google-daydream

But that also didn't help. How can that be? Thanks

**Comment by kaleknavicius** [comment]
Ok so for now the only workaround that I found was:

1. Scan a random QR code of some other cardboard (found on google images) which switches the way my Build is being displayed on Pixel screen.
2. Put my phone into Daydream viewer with NFC turned on.
3. Then when the phone is inside, NFC kicks in, switches VR settings to Daydream automatically and the same error pops up saying that this cardboard app is not compatible with my Daydream.
4. Then I cancel the error. Go into settings, disable NFC, put the phone back into Daydream viewer and then it works...

Up until I close the app. If I want to run it again, I have to re-do all the steps. Must be a better way haha...

**Comment by small-potatoes** [comment]
Hi kaleknavicius!  Unfortunately, there is currently no official support for running cardboard applications in the daydream viewer.

**Comment by Selzier** [comment]
Reason #997 not to purchase or develop for Gaydream

**Comment by chaosemer** [comment]
This is working as intended.

Daydream does not support current Cardboard apps because Cardboard apps do not enable async reprojection nor do they enable low persistence mode. Async reprojection is a technology that allows an app to reduce the [motion to photon latency](http://www.chioka.in/what-is-motion-to-photon-latency/). Getting an extremely low motion to photon latency is critical to avoiding motion sickness in VR experiences. Low persistence mode allows the screen's display to display pixels for a shorter amount of time, which avoids the blur that happens with normal displays.

Both of these features are required to run on Daydream to ensure a high quality VR experience. I'd suggest instead building your app for Daydream instead of Cardboard as you'll create a much better experience. Basically, you'll have to switch "Cardboard" to "Daydream" in the VR platforms supported dropdown and check the Daydream controller's touchpad instead of the Cardboard button. Otherwise the APIs are identical.

**Comment by GameFaceLabs** [comment]
are you selecting cardboard instead of daydream in the unity player vr settings?
