### ISSUE TITLE
import GoogleVRForUnity error

### ISSUE THREAD

**Issue by andy112247** [googlevr/gvr-unity-sdk#470]
![yz00kfc](https://cloud.githubusercontent.com/assets/22829656/23099494/981e94be-f6a3-11e6-969a-b29297821dd6.png)

I just import GoogleVRForUnity(GVR Unity SDK v1.20.0) on Unity 5.5.1f1
but more than 999+ error
like 
Assets/GoogleVR/Demos/Scripts/ScrollingUIDemo/PaginatedScrolling/PageProviders/ChildrenPageProvider.cs(1,0): error CS1525: Unexpected symbol `Per'

Assets/GoogleVR/Scripts/Controller/GvrPointerManager.cs(1,0): error CS1525: Unexpected symbol `_xlat24'

Assets/GoogleVR/Scripts/GvrUnitySdkVersion.cs(3,81): error CS1056: Unexpected character `?'

(this is my first First issue (*ﾟ∀ﾟ*)

**Comment by synthercat** [comment]
1. Are you sure you imported the whole .unitypackage?
2. Is this a new empty project?
3. Have you imported the additional files Unity askes after you import the GVR SDK?
(these usually hide and you have to minimize and re-maximize Unity to see the window for that)

**Comment by andy112247** [comment]
![1](https://cloud.githubusercontent.com/assets/22829656/23133235/69e90f24-f7cb-11e6-8834-f2e8952206ec.png)
![2](https://cloud.githubusercontent.com/assets/22829656/23133238/69efe786-f7cb-11e6-810c-84ab2728bd5b.png)
![3](https://cloud.githubusercontent.com/assets/22829656/23133237/69eef0ec-f7cb-11e6-9d1c-abe2bd21a703.png)
![4](https://cloud.githubusercontent.com/assets/22829656/23133236/69edddd8-f7cb-11e6-998d-c805184137e9.png)

Thank you for your reply
This is my step
i try gvr-unity-sdk-1.0.3 on unity5.5.1f1 it is work

**Comment by synthercat** [comment]
"The unable to parse file " errors usually associate with
a. Errors in paths (I see non-english letters on the third window) I'd bet this cause the problem 
b. If you don't have administration right to these files
c. .svn or git conflicts on the meta files (http://druss.co/2014/09/fixed-unable-to-parse-yaml-file-in-unity-3d-project/)

Here is what I would try to fix the problem in case of (a)
1. create a simple empty project
2. close unity
3. move the whole project (the one you just created) folder to a path as simple as possible like the "C:\" root of you hard drive. It should not have non English letters. I am Greek and avoid Greek characters because sometimes they could cause issues. Even long pathnames could do that on Windows 10 sometimes
4. reopen unity (DO NOT SELECT ANY PROJECT)
5. press the open button (on the top bar)
6. Search and select the folder you moved your folder (see number 3)
7. Now, import GVR
I hope this will fix your issues

Note : In the beginning you said GVR SDK version was 1.20 at your last post 1.0.3. Are you sure you are not using something older that these two? (these should both work fine, I can't say anything about prior to version 1.0 though)

**Comment by andy112247** [comment]
本機>DATA(D)>gvr-unity-sdk-master     =    D:\Unity\gvr-unity-sdk-master
本機=my computer
but Real path is D:\Unity\gvr-unity-sdk-master (There will be no non-english words
(i dont know how to explain it in English sorry 




![5](https://cloud.githubusercontent.com/assets/22829656/23134550/31cd4466-f7d0-11e6-8777-fd5c5007a9a2.png)

I reopen the unity ...
![6](https://cloud.githubusercontent.com/assets/22829656/23134918/8a796602-f7d1-11e6-9bb5-8cba87107193.png)

**Comment by synthercat** [comment]
First you reopened and THEN you tried to import the Google VR SDK, right?
Are you using SVN or git?

**Comment by andy112247** [comment]
I found it can work on Unity 5.0.1p1!!


I did it again 

1. open Unity 5.5.1f1
2. import the Google VR SDK (v1.20.0)

999+ error
 reopen unity
999+ error

3. import GVRBackwardsCompatibility.unitypackage
4. import  GVRVideoPlayer.unitypackage

 reopen unity
999+ error

i used Clone or Download>Download zip

**Comment by chaosemer** [comment]
The VR SDK does not support Unity 5.5. You either need to use 5.3, 5.4, or the 5.6 beta.
