### ISSUE TITLE
Null GVR context pointer, could not get GVR user prefs' handedness

### ISSUE THREAD

**Issue by vinhui** [googlevr/gvr-unity-sdk#491]
I get this error on device (pixel) with the latest sdk (1.30) on unity 5.6.0b10
I continuously throws this error. It doesn't seem to have too much impact but it's annoying when trying to debug

**Comment by miraleung** [comment]
I haven't been able to repro with the sample projects on b10, SDK 1.3. Could you please check the version of VrCore you're using, and confirm if the Daydream app is installed?

**Comment by vinhui** [comment]
We still have the issue with sdk 1.3 on unity 5.6.0f1 on a Moto Z with Google VR Services 1.3.149854881 and probably the on the pixel as well. It might have something to do with enabling and disabling vr mode

**Comment by Marchelune** [comment]
I also run into this with SDK 1.4 on Unity 5.6.1f1 when the first device listed in the "Virtual Reality SDKs" settings is _None._

It seems that it comes from the `Handedness` property, which calls `VRDevice.GetNativePtr()` but I guess it returns `IntPtr.Zero` with the _None_. 
And it is called after each end of frame in the GvrController, thus the debug flooding. 

Should we manually deactivate the GvrController in such case ?

**Comment by Flameshot** [comment]
Any solution for this? I have Unity 2017 with last unity gvr sdk 1.70. I export the project in android studio and then build with it. But when the app starts on device I have this error "Null GVR context pointer, could not get GVR user prefs' handedness"

**Comment by fredsa** [comment]
@Flameshot  I wonder if your final apk is incomplete, since you said you're exporting the Android Unity project to Android Studio and then building the app from there. Have you tried using Unity to **build and run** the app directly from the Unity editor?

Just a few more questions to try to narrow this down:

1. What's the exact version of Unity 2017 you're using?
1. What model phone are your seeing this on?
1. What Android version is the phone running (**⚙ > About phone ** Android version**)?
1. What do you have in the Daydream app under:
    * **☰ > Settings > Headset**
    * **☰ > Settings > Controller**
1. If you have enabled **Developer options**, what do you have for:
    * **☰ > Settings > Developer options > Enable GVR SDK library loading**

1. Finally, do you see any error messages in the device logs (`adb logcat`) when this right before the _Null GVR context pointer_ log message appears?

**Comment by Flameshot** [comment]
@fredsa Hello and thanks for answering. 
I'm using Unity 2017.1.0f3. I'm using a Samsung Galaxy S4 with Android 5.0.1 as a device and a Cardboard. 
I want to mention that if I build and run on device the "VideoDemo" scene it works. The thing is I am using some custom things and I need first to export in android studio. Before having the "Null GVR context pointer" error I have this error when it tries to load the video "file is compressed, not supported" and for the codec video I use VP8 and H264. 
I think I have this problems because of AndroidManifests merging and android studio is not adding the cardboard manifest? I don't know really

**Comment by fredsa** [comment]
First thing I'd suggest is to get a working apk by building directly from Unity. You can then use this apk and compare it to the one you're getting out of your Android Studio build.

A quick thing to check are the contents of the apk, especially libraries, which you can see by treating the apk as a zip:
```bash
unzip -l *apk | grep lib
```

You can compare manifests entries of the working and non-working app using `aapt` from the Android SDK:
```bash
aapt l -a *apk
```
Note that the AndroidManifest.xml entries won't be shown as XML, but the output is readable and you can compare the two side by side.

**Comment by Flameshot** [comment]
@fredsa  I forgot to mention that I am using Google Cardboard not Daydream

**Comment by fredsa** [comment]
Player Handedness is only relevant for Daydream.

Can you tell me which Gvr* prefabs or scripts you're using in your scene?

**Comment by rusmaxham** [comment]
If this is still an issue, please re-open with more details.

**Comment by fredsa** [comment]
Note, there were a few fixes in 1.100.0 for cases where `VRDevice.GetNativePtr()` could return `IntPtr.Zero` that weren't checked in earlier release.
