### ISSUE TITLE
Audio - Spatialize Post Effects.

### ISSUE THREAD

**Issue by rampartisan** [googlevr/gvr-unity-sdk#510]
Hey,

I have asked this question on stack but maybe I will have better luck here. I am using GVR Audio essentially only for the HRTF, I am developing my own reverb as part of an academic project, and I therefore need to apply this reverb before the HRTF's kick in. 

With standard unity audio sources you have the option to spatialize post effects, meaning any plug-ins I create or OnAudioFilterRead() calls will happen before the HRTF. Is there such a method for GVR audio sources, or a recommended way of solving this problem?

Thanks.

**Comment by anokta** [comment]
Hi,

The short answer is **yes**. :) 

I have just replied to [the StackOverflow thread](http://stackoverflow.com/a/42984210/1008760) for more information - assuming that is the same thread you referred to.

Cheers

**Comment by rampartisan** [comment]
Thanks! I went ahead and edited the audiosource cs and editor cs too, so now I have the option within the editor.

I have an add on question, which fits better over here...

Is there a particular reason why the spatailze post effects option is not included by default in the GVRAudioSource scripts? (if you happen to know!)

**Comment by anokta** [comment]
No problem! 

The main reason why it's not there yet is due to the AudioSource requirement for the default audio effect components (as mentioned in the thread), where we still look into ways to better support.  

Nonetheless, there is nothing major blocking this change, and yet, the feature itself was only introduced by Unity 5.5+, so you may expect this option be enabled by default in the next SDK update.

Cheers
