### ISSUE TITLE
Project upgraded from Google Cardboard to Google VR runs in Unity but fails when building for iOS (XCode or Unity Cloud Build)

### ISSUE THREAD

**Issue by Claus79** [googlevr/gvr-unity-sdk#518]
Please check my question in Unity Answers: http://answers.unity3d.com/questions/1333075/project-runs-in-unity-but-fails-when-building-for.html

**Comment by chaosemer** [comment]
@miraleung, can you comment on this?

**Comment by cdepace** [comment]
I have updated it:

I started my project using Google Cardboard then I imported the new GoogleVR package to replace it. When I hit play in Unity my project works fine but when I try to build it for iOS I get errors on both the Xcode project and the Unity Cloud build project. I'm using Unity v5.5.0f3 on Mac

**On Xcode:**

```
 ld: warning: arm64 function not 4-byte aligned: ltmp0 from /Users/gamedev/Desktop/VR1-iOS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
 ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/gamedev/Desktop/VR1-iOS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
 Undefined symbols for architecture arm64:
   "_endSettingsDialog", referenced from:
       -[DismissDialogViewController viewDidAppear:] in libvrunity.a(unity.o)
 ld: symbol(s) not found for architecture arm64
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
**on Unity cloud build:**

  ```
[xcode] Undefined symbols for architecture armv7:
 9352:        [xcode]   "_endSettingsDialog", referenced from:
 9353:        [xcode]       -[DismissDialogViewController viewDidAppear:] in libvrunity.a(unity.o)
 9354:        [xcode]   "_isOpenGLAPI", referenced from:
 9355:        [xcode]       RegisterMonoModules() in RegisterMonoModules.o
 9356:        [xcode] ld: symbol(s) not found for architecture armv7
 9357:        [xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)
 9358:        [xcode] Showing first 200 warnings only
 9359:        [xcode] ** ARCHIVE FAILED **
 9360:        [xcode] The following build commands failed:
 9361:        [xcode]     Ld /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-gccgnjkpqhormzcosgksevxlzeea/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/vr1.app/vr1 normal armv7
 9362:        [xcode] (1 failure)
```
 
I've noticed that most of the answers to this kind of problem refer to SourceTree (This is what I'm using) ignoring .dll file when pushing the source code. At the moment I don't have any .gitignore file in my working directory.

**Comment by cdepace** [comment]
They only way to solve it was:

 - Removing GoogleVR plugin (and all references to it) in my project
 - Replacing the GazeVR view tracking with a simple Raycasting in order to activate specific methods on the object the user is looking to
 - Activating virtual mode in the "Building Setting" when exporting to iOS
 - Removing `libvrunity.a` and `libgvrunity.a` libraries from the XCode project
 - Assuring the Bitcode support is set to NO
 - Importing GoogleVR as cocoapod.

Unfortunately this procedure prevents me from displaying the Stereo View in the Unity Editor.

In the Unity forum users are saying that version 1.30 doesn't support native iOS in Unity 5.6. When can we except an update?

**Comment by rusmaxham** [comment]
This should be fixed in Unity Cloud build now.
