### ISSUE TITLE
Reticle shakes when entering UI Button

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/gvr-unity-sdk#521]
On 5.6.0f2 with SDK 1.30 the reticle shakes when entering UI Buttons but not when hovered on Mesh colliders with Event Trigger. It also only appears on Game view and not Scene view so probably a rendering issue rather than a positioning issue.

Demo scene works nicely but this happens when I set up using prefabs. I also put interactibles in a layer called UI.

Attached is a video of the issue:
[GoogleVR-ReticleShake.zip](https://github.com/googlevr/gvr-unity-sdk/files/887062/GoogleVR-ReticleShake.zip)

**Comment by chaosemer** [comment]
Thank you for the bug report, I've added it to our internal tracker.

**Comment by guneyozsan** [comment]
Issue persists with 5.6.0f3.

It also happens when I setup the objects manually, not special to prefabs as I mentioned above.

**Comment by mattfedocsg** [comment]
Question, because Ive come across this before as well.  What is the distance that the cursor is set to?  Ive noticed this "pop" effect when the cursor is a standard far distance (say local to 10) and then hovers over a UI element that is, say local of 2.  Mainly because the reticle needs to update its position quickly to get closer to the camera while opening.  I think what I did before was scale down the cursor and lessen the distance it is away from the cameras.

**Comment by mattfedocsg** [comment]
Check this video of the distance pop.

[ReticleIssue.mov.zip](https://github.com/googlevr/gvr-unity-sdk/files/920796/ReticleIssue.mov.zip)

**Comment by guneyozsan** [comment]
In my case, the reticle hovers to the UI button coming from the plane on the background which is quite close, so both near 10 meters away from camera. It also does the same from infinity to buttons located at 20-30 meters.

My workaround was to replace all UI Buttons with Mesh Colliders with Event Triggers.

**Comment by Mozis** [comment]
These might be two different problems.

I had a shake when I was using unity's graphics raycaster instead of gvr raycaster on my canvas. It can be removed by commenting out a line "pointer.OnPointerEnter(...)" in GvrPointerInputModule > UpdateReticle() method (around line 300).
BUT as much as I want the default raycaster, just commenting that out is not efficient. Having no gvr raycaster creates a new placeholder ray every single frame ( look at GetLastRay() method in GvrPointerInputModule).

And another shake was from RETICLE_DISTANCE_MAX in GvrReticlePointerImpl.cs being too much. Using gvr raycaster or commenting out that line I mentioned does not help in this case. You just need lower distance.

**Comment by dsternfeld7** [comment]
Thanks for the report! Are you still able to reproduce this issue in the 1.100 version of the SDK? If so, can you provide steps to reproduce the issue in an empty scene?

**Comment by Mozis** [comment]
I totally would try that, but it would take too much time, I think. I don't remember the setup that caused the problem for me. I got it fixed and moved on.
Maybe someone else can try the new version out.
