### ISSUE TITLE
X button does nothing

### ISSUE THREAD

**Issue by andyz** [googlevr/gvr-unity-sdk#564]
With GVR 1.4 and Unity 5.5.1:
The X button top-left has no effect on android or iOS - does not seem to even send an event to Unity, nevermind close the app.
What should it do?

**Comment by tedruxpin** [comment]
We are investigating this issue, thank you for bringing it to our attention.

**Comment by miraleung** [comment]
As per the example in GVRDemo (Assets/GoogleVR/Demos/Scripts/DemoInputManager.cs), you can check for Input.GetButtonDown(KeyCode.Escape) in Update() and implement the desired behaviour.

**Comment by andyz** [comment]
What? It should do that but it does not, the android back button sends this event not the X

**Comment by camilosw** [comment]
I don't understand why you closed this issue. I'm also using GVR 1.4 and Unity 5.5.2. I tested the GVRDemo and tested with custom code and X button doesn't work.

You also has a typo in your response. Input.GetButtonDown method doesn't accept a KeyCode as parameter. DemoInputManager use Input.GetKeyDown instead of Input.GetButtonDown. Is there something we are missing?
