### ISSUE TITLE
crashes in 'VR Mode Enabled' switch

### ISSUE THREAD

**Issue by xiesi88** [googlevr/gvr-unity-sdk#565]
When I try to Enable VR Mode in runtime, frame rate drops quickly,and after a while the application crashes.
im using Unity5.6 and GVR1.40.

This seems to be an old problem, I found other friends have encountered this problem a long time ago,it seems that the problem first appeared in the GVR0.9.1 version

**Comment by xiesi88** [comment]
if i enabled vr mode at runtime, then load to a new scene, app crashes on android smartphone.

i'm using unity5.6.0f3 + GVR1.40

**Comment by miraleung** [comment]
Could you please clarify the C# code you're using? FYI, GvrViewer source doesn't run on-device, and its enableVrMode shouldn't be used. Instead, please refer to #532 for toggling VR Mode at runtime.

**Comment by xiesi88** [comment]
IEnumerator LoadDevice(string newDevice)
    {
        VRSettings.LoadDeviceByName(newDevice);
        yield return null;
        VRSettings.enabled = true;
    }

**Comment by lachlansleight** [comment]
I have this problem, and have done a bunch of research to try and isolate - here's what I've found:

There are three broad cases - including both daydream and cardboard as VR devices in PlayerSettings, including only daydream, or including only cardboard.

* Including both results in a total failure to enable VR mode on cardboard devices, and results in the below list of errors on daydream devices. 
* Including only cardboard works on cardboard devices (although it does spam GL_INVALID_VALUE errors to logcat each frame), and results in the 'incompatible app' error on daydream devices (which 99% of users will fail to get past since it's required every time)
* Including only daydream results in the below list of errors on daydream devices, and bars cardboard devices from entering VR mode

---

# The errors

Creating an empty Unity project and building four scenes recreates the problem.

Scene 1 is a 2D scene with a button to launch in VR. Pressing the button opens scene 2
Scene 2 is an interstitial scene that runs this coroutine, then opens scene 3.

```C#
UnityEngine.VR.VRSettings.LoadDeviceByName("daydream");
yield return null;
if(!UnityEngine.VR.VRSettings.loadedDeviceName.Equals("daydream")) {
	Debug.LogWarning("Waiting one more frame for enabling daydream");
	yield return null;
}
UnityEngine.VR.VRSettings.enabled = true;
if(!UnityEngine.VR.VRSettings.enabled) {
	Debug.LogError("Failed to enable VR settings!");
}
```
Scene 3 is a scene to view in VR - just a skybox and a script to load Scene 4 when the 'back' button is pressed (`Input.GetKeyDown(KeyCode.Escape))`)
Scene 4 is another interstitial scene that runs this coroutine, then opens scene 1

```C#
UnityEngine.VR.VRSettings.LoadDeviceByName("None");
yield return null;
if(!UnityEngine.VR.VRSettings.loadedDeviceName.Equals("None") && !UnityEngine.VR.VRSettings.loadedDeviceName.Equals("")) {
	Debug.LogWarning("Waiting one more frame for disabling daydream/cardboard");
	yield return null;
}
UnityEngine.VR.VRSettings.enabled = false;
if(UnityEngine.VR.VRSettings.enabled) {
	Debug.LogError("Failed to disable VR settings!");
}
```

Upon returning to scene 1 (i.e. during the coroutine running in scene 3), the following error messages are logged to the console:

```
05-30 17:41:49.910  8233  8259 E Unity   : [EGL] Failed to create window surface: EGL_BAD_ALLOC: EGL failed to allocate resources for the requested operation.
05-30 17:41:49.910  8233  8259 E Unity   : (Filename: ./Runtime/GfxDevice/egl/WindowContextEGL.cpp Line: 141)
05-30 17:41:49.910  8233  8259 I Unity   : Skipped rendering frame because GfxDevice is in invalid state (device lost)
05-30 17:41:49.910  8233  8259 I Unity   : (Filename:  Line: 772)
```

Then, upon entering scene 3 again, the following log output is seen:

```
05-30 17:41:54.602  8233  8259 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range
05-30 17:41:54.602  8233  8259 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 383)
05-30 17:41:54.738  8233  8259 E Unity   : [EGL] Failed to create window surface: EGL_BAD_ALLOC: EGL failed to allocate resources for the requested operation.
05-30 17:41:54.738  8233  8259 E Unity   : (Filename: ./Runtime/GfxDevice/egl/WindowContextEGL.cpp Line: 141)
05-30 17:41:54.738  8233  8259 I Unity   : Skipped rendering frame because GfxDevice is in invalid state (device lost)
05-30 17:41:54.738  8233  8259 I Unity   : (Filename:  Line: 772)
05-30 17:41:54.924  8233  8259 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range
05-30 17:41:54.924  8233  8259 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 383)
05-30 17:41:54.936  8233  8259 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range
05-30 17:41:54.936  8233  8259 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 383)
05-30 17:41:54.962  8233  8259 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range
05-30 17:41:54.962  8233  8259 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 383)
05-30 17:41:54.979  8233  8259 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range
05-30 17:41:54.979  8233  8259 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 383)
```

(The GL_INVALID_VALUE error repeats every frame until I return to scene 1)

After an irregular number of times (somewhere around the 2-5 marks) of entering and exiting VR, the application crashes when returning to scene 1 (i.e. upon disabling VR)

---

This is actually a huge problem as it totally precludes any 2D app that features VR from using the native VR integration, as all phones paired to a daydream headset will either show the 'Incompatible app' error (which is effectively a brick wall for most users) if daydream hasn't been included in Player Settings, or crash if it has. Once the S8 adds daydream support, this will be a substantial number of Android devices.

**Comment by guneyozsan** [comment]
Did you also try delaying the initial call a few frames away from Start()?

Guney Ozsan
Game Developer, Composer, Sound Designer, Artist
guney@guneyozsan.com
+90 532 6471901
www.guneyozsan.com

**Comment by lachlansleight** [comment]
I've been doing a single yield return null at the beginning of my coroutines - I didn't include it in the above script extracts but I'll edit it in for completeness.

Do you have success when using multiple yield return nulls?

**Comment by Dhawal4m** [comment]
Using Unity version 5.6.1p1(patch release) seems to resolve this issue. It did it for me. The spamming with OPEN_GL error has stopped.

**Comment by lachlansleight** [comment]
I don't see any relevant patch notes in 5.6.1p1 - any confirmation about this @[anyone from unity or google]?

At this point I've reverted to 5.5.3 since the native integration is unusable.

**Comment by harprasad** [comment]
I was also getting the same error even without switching VR mode. My app crashed whenever I looked at a particular building.It seems the material on the building was causing this. I changed the material type to mobile/bumped diffuse from standard and the error is gone.

**Comment by WelchCompositions** [comment]
Appreciate the mention @lachlansleight of different combinations of daydream and cardboard support. My app isnt intended for daydream so I didnt include it but without daydream support included cardboard froze after about 10-15 seconds after enabling vr mode wevery single time without fail after the same duration. The cardboard overlay buttons still worked but the cameras appeared frozen and didnt track. Adding daydream support was the fix for me! (unity 5.6.1)

**Comment by fredsa** [comment]
I believe the problems described in this issues have all been fixed in recent updates.

At this point I would recommend using the most recent release build of Unity 5.6 (or 2017), which will have the latest version of the Google VR native integration.

To switch between VR and non-VR mode, see https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime.

**Comment by fredsa** [comment]
Closing this issue for now. Please reopen if you're still having problems. In that case it would be helpful to know:
- Specific Unity version
- Google VR SDK version
- Phone manufacturer / model
- Android version (**Settings > About phone > …**)
- And, ideally, version of Google VR Services (**Settings > Apps > ⋮ > Show system > Google VR Services**)
- Log output (`adb logcat`)
