### ISSUE TITLE
Lag on Huawei P8 Lite

### ISSUE THREAD

**Issue by Kaendan** [googlevr/gvr-unity-sdk#573]
Hi!

I created an app for cardboard with Unity and the GoogleVR SDK. It works fine on many phones but when I tested it on a Huawei P8 Lite even if it launched, that was lagging a lot. It's simply not usable.

So I made a test, I created a new Unity project, followed instructions to make a new project with GoogleVR. I Built the GVRDemo, it works on other phone but not with the Huawei P8 Lite. It's still lagging

I guess that it comes from a compatibilty problem with GVR and this phone ?
The Huawei P8 Lite on the other hand can work with some VR games that I tested. It also works fine with Cardboard Design Lab.

I can't find why it's not working. That just a new project with the GVRDemo and it works on other phones, older phones. I would say that it comes from the Huawey P8 but it works fine with other VR apps I tested and Cardboard Design Lab

Thanks for you help

**Comment by miraleung** [comment]
Could you please clarify which version of Unity, and whether Daydream or Cardboard is enabled in Player Settings?

**Comment by Kaendan** [comment]
I am using Unity 5.6.0f3. Cardboard is enabled in Player Settings. I am using GVR 1.40

**Comment by miraleung** [comment]
Thanks for clarifying. Could you please post a video of the lag so we can better investigate?

**Comment by Kaendan** [comment]
Here is the video : https://www.youtube.com/edit?o=U&video_id=Sx38p941OXk

**Comment by Kaendan** [comment]
Here is the video : https://youtu.be/Sx38p941OXk

**Comment by nathanmartz** [comment]
Sounds like a phone specific issue, and CDL is built using some very custom opimizations.

**Comment by pezvolador** [comment]
I have the same exact problem. Have tried with other (most recent) unity and GVRSDK versions but still no improvement. Anyone?

**Comment by pezvolador** [comment]
I think it has something to do with the phone not having a gyroscope. Not 100% sure but... It looks like that is the problem.

**Comment by Jeysam1** [comment]
i have Huawei GR5 2017 , and i'm having same issue

**Comment by nathanmartz** [comment]
Yes, a hardware gyro is required for a reasonably good experience.

**Comment by chelder86** [comment]
Hi. One of our customers have reported a VERY similar issue. He said it's working well with Cardboard Design Lab, but it's slow with our game (built also in Unity). He says it works well turning from right to left but not up to down (or the opposite: I don't remember exactly).

He has reported that this issue is with two different Huawei models: 
- Huawei P8 lite 2017
- HUAWEI P smart

@nathanmartz , **both models have a gyro according to the Google Play data**. Actually our customer also say it's working well with Cardboard Design Lab.

**Comment by rusmaxham** [comment]
If your customer is reporting that Cardboard Design Lab works well, but your app doesn't, this no longer sounds like a device-specific issue, but an app-specific issue.  Without knowing what your app is doing, it is difficult to speculate on what the root cause is.  I would suggest using the Unity profiler to examine your app's performance.

**Comment by rusmaxham** [comment]
Unfortunately, we're only able to address issues with the GVR SDK for Unity and aren't able to address all device-specific issues.

**Comment by chelder86** [comment]
>  we're only able to address issues with the GVR SDK for Unity
@rusmaxham The game is built with it

> and aren't able to address all device-specific issues
OK. I understand. There are thousand of models and most Huawei smartphones didn't have gyro last year. This year, it seems they began to add it in their models more often. So I guess that's why GVR SDK for Unity is not working well with it yet.

Thanks for your support and I hope our feedback is useful

Carlos
