### ISSUE TITLE
GvrControllerState incorrect

### ISSUE THREAD

**Issue by vinhui** [googlevr/gvr-unity-sdk#581]
`GvrController.State == GvrConnectionState.Connected` returns true on a fixed interval (seems like a second) in editor when the controller emulator app is not running on a mobile device attached (adb wireless and wired), the other frames it returns `GvrConnectionState.Connecting`. When no device is attached, this is not happening.

Using Gvr v1.50 with Unity 5.6.0f3

**Comment by chaosemer** [comment]
Thanks for the bug report, we will investigate.

**Comment by rusmaxham** [comment]
Is this still an issue with the latest SDK v1.100.1?

**Comment by fredsa** [comment]
Looks like we failed to mention this in the release notes, but I believe this issue was fixed in either 1.60 or 1.70 of the SDK.

The cause was the way that the EmulatorClientSocket script managed state. This script does [indeed](https://github.com/googlevr/gvr-unity-sdk/search?utf8=%E2%9C%93&q=Thread.Sleep%28%28int%29+%28toWait+*+1000%29%29%3B) poll at a one second interval.

Please let us know if this not fixed in the latest release.
