### ISSUE TITLE
iOS - "GVROverlayView.h" not found

### ISSUE THREAD

**Issue by ankitjain8790** [googlevr/gvr-unity-sdk#588]
I have Unity 5.6.1f1 and googlevr 1.50 installed. After doing all the cocoa pods settings I build and getting error like "GVROverlayView.h" not found.
I have this file in Pods/GVRSDK/Sources
I tried removing and re-referencing but it do not works.
Please shed some light as its very urgent.

**Comment by miraleung** [comment]
Could you please post the full error logs, and confirm your version of XCode, targeted iOS version, and whether the Pod was originally generated by Unity? 

A few other things to try:
- Before Pod-updating, delete the Pods directory from within XCode
- Delete the xcodeproject before doing subsequent rebuilds from Unity - cached state may not always be overwritten

**Comment by cezarbabin** [comment]
Make sure you're opening the .xcworkspace not the .xcodeproj.

**Comment by ankitjain8790** [comment]
@miraleung I have XCode 8.2.1. I am deleting the pods directory before updating and installing it.
@cezarbabin I am opening the workspace only thats why pods are getting build.

**Comment by ankitjain8790** [comment]
![screen shot 2017-05-24 at 12 41 47 pm](https://cloud.githubusercontent.com/assets/4799086/26399746/6c8bf0d8-407e-11e7-930a-7a0bc1169c68.png)
This is the error I am getting

**Comment by guneyozsan** [comment]
For "GVROverlayView.h" not found error in 5.6.0f3 and 1.30 using -IPods/GVRSDK/Sources linker flag or using the trick here: https://github.com/googlevr/gvr-unity-sdk/issues/504#issuecomment-292692060 works. You can try that.

**Comment by fredsa** [comment]
We've updated the [Get started with Google VR in Unity on iOS](https://developers.google.com/vr/unity/get-started-ios) guide. The new guide includes a note about the importance of opening the generated `*.xcworkspace` file instead of the `*.xcodeproj` file.

Closing this issue as I believe the above problems are fixed by a combination of:
* Updating to the latest Unity 5.6 or Unity 2017 release
* Updating to the latest Google VR SDK for Unity
* Opening the the generated `*.xcworkspace` Xcode workspace
* Following the steps in the above mentioned getting started guide

@ankitjain8790 Please let us know (by filing a new issue) if you encounter any issues creating a working Xcode project using the latest Unity 5.6 or Unity 2017 and the latest Google VR SDK for Unity using the updated guide.

**Comment by rinkusarumpllc** [comment]
Hi there,
I'm using Unity2017.20f3 latest version where cardboard is supported inbuilt and I don't need to download the GVR sdk.
After downloading the pod file I'm facing this issue please guide me what should i do.

**Comment by rusmaxham** [comment]
Did you open the .xcodeproj file or the .xcworkspace file when opening the project in Xcode?

**Comment by rinkusarumpllc** [comment]
I open the .xworkspace file however the error hours when i change the
target to 8.0

**Comment by rusmaxham** [comment]
Do you see this in your xcode project navigator?

![screen shot 2017-11-07 at 12 24 50 pm](https://user-images.githubusercontent.com/13911074/32516171-4b519906-c3b7-11e7-94ef-830412f210c8.png)

**Comment by jy787805208** [comment]
> Do you see this in your xcode project navigator?
> 
> ![screen shot 2017-11-07 at 12 24 50 pm](https://user-images.githubusercontent.com/13911074/32516171-4b519906-c3b7-11e7-94ef-830412f210c8.png)

I have the same problem and i can't see files shown on your pic.
Any help?
