### ISSUE TITLE
How to stop or disable or pause head tracking 

### ISSUE THREAD

**Issue by Dabin22** [googlevr/gvr-unity-sdk#631]
I am currently using gvr-dunity-sdk 1.6 and unity5.6 

Finally build with Android app.

I do not want to use the screen rotation, transform with head tracking in some scenes.

Help me plz...

**Comment by guneyozsan** [comment]
In GVR 1.30 you can do this on your camera to disable head tracking.

    void Start()
    {
        gvrHead = GetComponent<GvrHead>();
   } 

and later use 
            gvrHead.enabled = false;

This is a legacy class. Not sure how it will be possible to do this in future versions.

**Comment by Dabin22** [comment]
@guneyozsan 
Thank you, but I do not seem to have GvrHead in 1.5 version

**Comment by PedroScreamerovsky** [comment]
i'm also interested in doing that, i've tried everything, the most similar result is to put the camera in a parent object that rotate in opposite way of the camera, but it's not perfect, quite jittery.

**Comment by nathanmartz** [comment]
Head tracking and stereo rendering are both required for VR rendering, so we don't allow them to be disabled independently anymore. You can simply disable VR mode entirely if you like.

**Comment by turgaysenlet** [comment]
A script for the main camera with the following code seems to disable the head tracking:

void Start () {
UnityEngine.XR.XRDevice.DisableAutoXRCameraTracking (GetComponent<Camera>(), true); 
} 

However, it is not completely turned off, it still tracks and re-centers the view frequently. 
My interest in doing this was to improve the performance of my app by shutting down tracking, since I don't need it for my app with a static view. Since tracking is still being done, it did not improve the performance. If you need it for a purpose other than improving the performance, it can help you.

**Comment by Griimaze** [comment]
just set the camera rotation to 0,0,0
https://youtu.be/_xiRtwZkmto
