### ISSUE TITLE
iOS build issues with Unity 5.6.2f1 and GVR 1.60

### ISSUE THREAD

**Issue by tb9will** [googlevr/gvr-unity-sdk#632]
Since updating to Unity 5.6 and GVR 1.60 I haven't been able to get a scene built and installed on an iOS device.
I will list all the steps i've taken below. If I am missing anything please let me know. 

- In Unity I have iOS as the selected platform.

 

- **Under Player Settings > Other Settings** - Virtual Reality Supported is check and Cardboard is the selected Virtual Reality SDK.

- From there I follow the instructions listed in the README here:

<img width="991" alt="screen shot 2017-06-23 at 10 14 23 am" src="https://user-images.githubusercontent.com/17855317/27485928-d3edf600-57fc-11e7-9823-4f84ef4f9c8b.png">

- Open the **Unity-iPhone.xcworkspace**

- After trying to build in xcode I get these errors:
![screen shot 2017-06-23 at 10 21 41 am](https://user-images.githubusercontent.com/17855317/27486196-cf574348-57fd-11e7-894c-ba68f14f698e.png)

- Go to **Project Settings > Build Phases > [CP] Check Pods Manifest.lock**. `diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null` My `${PODS_PROFILE_DIR_PATH}` and `${PODS_ROOT}` variables are not set correctly.

- Change them to point to the correct places: `diff "${SRCROOT}/Podfile.lock" "${SRCROOT}/Pods/Manifest.lock" > /dev/null`

- Attempt to build again and receive the `'GVROverlayView.h' file not found` error.

- Follow the steps found in the issue here: [#504 (comment)](https://github.com/googlevr/gvr-unity-sdk/issues/504#issuecomment-292692060)

- close the **.xcodeproj** and open the **.xcworkspace**

- Attempt to build again and get 108 Apple Mach-O Linker (id) errors:
![screen shot 2017-06-23 at 10 43 03 am](https://user-images.githubusercontent.com/17855317/27487117-c74167c6-5800-11e7-9912-4e9a3eeee057.png)

I'm stuck here and now sure what else to do. I've tried completely uninstalling Unity and reinstalling. 

Thanks for any help.

**Comment by justlim77** [comment]
Hey tb9will,

I was having the exact same problem as you did - until I traced back my steps and realized I forgot to delete the **Pod** folder that resided in the Unity-iPhone foldout within the Xcode project itself (not referring to the **Pods** folder in the Finder window). After ensuring that folder within Xcode project is deleted, repeat the steps again and you will find that it will build.

**Comment by Yerchick** [comment]
Also there is tiny possibility, that you could forgot to delete previous GVR SDK properly. I've had a lot of problems with that

**Comment by fredsa** [comment]
We've updated the [Get started with Google VR in Unity on iOS](https://developers.google.com/vr/unity/get-started-ios) guide. The new guide includes a note about the importance of opening the generated `*.xcworkspace` file instead of the `*.xcodeproj` file.

Closing this issue as I believe the above problems are fixed by a combination of:
* Updating to the latest Unity 5.6 or Unity 2017 release
* Updating to the latest Google VR SDK for Unity
* Opening the the generated `*.xcworkspace` Xcode workspace
* Following the steps in the above mentioned getting started guide

@tb9will Please let us know (by filing a new issue) if you encounter any issues creating a working Xcode project using the latest Unity 5.6 or Unity 2017 and the latest Google VR SDK for Unity using the updated guide.
