### ISSUE TITLE
Unity 2017.1, to use the controller, please upgrade a version of Unity with the GVR native integration

### ISSUE THREAD

**Issue by akira32** [googlevr/gvr-unity-sdk#663]
I open the GVRDemo scene, but it display the warning message in game view.

to use the controller, please upgrade a version of Unity with the GVR native integration

Does somebody know how to solve this problem?

**Comment by fredsa** [comment]
Hi akira32,

Are you referring to the text in Unity's "scene" view, which shows the warning message even before you hit play? If so, sorry about the confusion.

The message text is currently updated dynamically based on your current environment, but only at runtime, after you hit play.

Since the default text is pretty confusing right now we're changing the demo scene in the upcoming 1.70 release to only show an appropriate warning message at runtime, after you press play. (The static/default text in the scene will instead read something like "Messages will appear here at runtime".)

**Comment by akira32** [comment]
Thank you, fredsa!

**Comment by fredsa** [comment]
Fixed in 1.70.0
