### ISSUE TITLE
 library not found for -lGTMSessionFetcher

### ISSUE THREAD

**Issue by qiaonifengxue** [googlevr/gvr-unity-sdk#688]
error :  Showing Recent Issues ld: library not found for -lGTMSessionFetcher

Unity 2017.1.0f3 
Google ios  SDK 1.7 

How can I solve the problem?
<img width="880" alt="123123123213" src="https://user-images.githubusercontent.com/26831898/29309452-624d68aa-81dc-11e7-95d1-bd607ac553ac.png">

**Comment by rusmaxham** [comment]
Did you open the .xcodeproj or .xcworkspace file?

**Comment by qiaonifengxue** [comment]
open  .xcworkspace，But now the error is reported
<img width="1034" alt="qq 20170821162856" src="https://user-images.githubusercontent.com/26831898/29510293-e2c72ed4-868d-11e7-8d4f-609bbd75dbdd.png">

**Comment by thep3000** [comment]
I can not repro this issue on Unity 2017.1.0f3.  A blank project setup for cardboard (or a project with gvr-unity-sdk 1.7 sample scenes) builds and runs fine on iOS.

Can you provide a repro project or precise repro steps?  A longer log might help as well to see what duplicate symbols are being reported.

**Comment by fredsa** [comment]
We've updated the [Get started with Google VR in Unity on iOS](https://developers.google.com/vr/unity/get-started-ios) guide. The new guide includes a note about the importance of opening the generated `*.xcworkspace` file instead of the `*.xcodeproj` file.

@qiaonifengxue Please let us know (by filing a new issue) if you encounter any issues creating a working Xcode project using the latest Unity 5.6 or Unity 2017 and the latest Google VR SDK for Unity using the above guide.

**Comment by fredsa** [comment]
Duplicate of #539
