### ISSUE TITLE
Application.Quit() not going back to Android Home

### ISSUE THREAD

**Issue by jkeon** [googlevr/gvr-unity-sdk#708]
We're having an issue where we tap on the X button in the top left corner of the screen while in VR mode and we expect to quit back to Android home.

We're using Unity 2017.1.0p4 with GVR 1.70. Just like in the Google samples, we're calling the Application.Quit() function when we get the event to close from VR. 

Currently, it does close our app but then it goes back to whatever the previously opened app was instead of Android Home. For example if we were looking at weather and then launched our app and then closed from VR, it would go back to weather. 

Using a Google Pixel with Android 7.1.1.

**Comment by andrelevi** [comment]
I'm experiencing this issue as well. I believe it used to quit properly back when I was using an older version of Unity/GVR.

**Comment by reed-alpert** [comment]
I see the same thing for Unity Daydream apps on Pixel.XL/7.1.2 and Moto.Force/7.1.1. They both go back to the previous opened app.

Google Museum DAydream app does the correct thing and returns to Android 2D desktop. 

Using:
>> Unity 2017.1.0p5 / IL2CPP
>> GVR Unity SDK 1.60
>> Daydream Renderer 1.0
>> Android NDK r10e

**Comment by dustinkerstein** [comment]
I can also replicate this on Unity 2017.1.1p1 and GVR 1.7 using Application.Quit() when invoking my app via a deep link from Chrome.

And when launching inside of the Daydream app (in VR mode) calling Application.Quit() will return back to the Daydream app in VR mode, and then automatically quit to the 2D Android home in about 3 seconds - This particular behavior was noted here - https://forum.unity.com/threads/daydreams-native-x-quit-button-doesnt-quit-the-application.442942/

**Comment by bigfootaus** [comment]
Can replicate this on Unity 2017.2.0f2 and "GVR SDK for Unity v1.100.1". Calling Application.Quit () brings the app to the Daydream launcher in VR mode, and then a few seconds later crashes to the 2D Android home screen.

This is apparently preventing Daydream publishing for me; "When in VR, your app should never display any 2D images. Tapping on "Close Game" within the pause menu brings the user to the 2D Android home screen. It must return to the Daydream home screen."
Doesn't match up with another publishing requirement (FN-A2 wants us to go back to the 2D phone launcher instead of VR?) but still, it's all connected to this bug too.

**Comment by rusmaxham** [comment]
We are working with Unity to resolve this issue.

**Comment by nathanmartz** [comment]
Just to be clear, the expected behavior is that calling Application.Quit() while in Daydream mode should return you to the 2D android launcher. There are cases where you may get a few sections of the previous app showing, but that shouldn't cause a DFX submission rejection.

I believe @bigfootaus issue is different. They have a "Close Game" button in VR which they expect to exit the app and return to Daydream Home, but they call Application.Quit() which conflicts with the above. The easiest fix is to simply not have an app specific "Close App" button as users can do that at any point just by pressing the Home button. If you feel you have to have such a button, then you need to fire off the right intent to launch Daydream Home, not exit your app.

**Comment by bigfootaus** [comment]
Ah thanks Nathan, I didn't even consider that the "Close Game" button could just be removed without affecting users' ability to exit the game. That should resolve that publishing issue for me =)

**Comment by rusmaxham** [comment]
This is now fixed in Unity 2017.1.2p4, 2017.2.1f1, 2017.3.0f2.  A patch for 5.6 is coming as well.

**Comment by ylluminarious** [comment]
Can confirm that this seems fixed in Unity `2017.3.0f3`.
