### ISSUE TITLE
iOS Cardboard Transition View doesn't respect flag

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#714]
It looks like this was documented in #593 but a separate issue was never created.

Tested on Unity 2017.1.0p5 and GVR iOS CocoaPod 1.6

Regardless of the "Enable Transition View" flag, when `VRSettings.LoadDeviceByName ("cardboard") ` is run the Transition View will be shown.

**Comment by Ethan-VisualVocal** [comment]
@dustinkerstein We've been holding off on a release because of this, and thankfully (hopefully) this was fixed in 2017.1.1p1 (https://unity3d.com/unity/qa/patch-releases)

> - (940917) - iOS : Cardboard Enable Transition View fix added.

Which has a bug number that, confusingly, doesn't align with the other reported bug here: https://issuetracker.unity3d.com/issues/ios-cardboard-splash-screen-appears-even-if-enable-transition-view-is-set-to-false 

No idea whose bug it was, ultimately. Could have been fixed by Google b/c the patch notes also say: 
> - XR : Updated Google VR NDK to 1.80.

I'll add a comment here later to confirm fixed status.

**Comment by dustinkerstein** [comment]
Just gave it a quick test and it does indeed appear to be fixed in 2017.1.1p1
