### ISSUE TITLE
Video Controls feedback on Hover

### ISSUE THREAD

**Issue by Vathsal** [googlevr/gvr-unity-sdk#717]
Hi all, 

I was working with the video controls provided in the samples. From a UX research perspective, we found that having some feedback on hover over the play/pause button seems to be more intuitive. I was glancing through the VideoControls prefab and the VideoControlsManager.cs script, but found no option to add that. Could anyone provide some insights on how I could implement this?

I could always inherit from the VideoControlsManager.cs class but it seems to be a very messy approach. How would you suggest I customize the controls for my specific application ?

Thanks

**Comment by dsternfeld7** [comment]
I would recommend that instead of starting with the video controls included in the SDK, that you use the Media App Template (https://developers.google.com/vr/unity/media-app-template) as your starting point.

The video controls included in the SDK is meant to simply be a basic example of how to play video, but the Media App template is mean to demonstrate best practices for the UX of playing videos. It includes playback controls that should be easier for you to modify and extend.
