### ISSUE TITLE
GvrPointerPhysicsRaycaster only works if GvrReticlePointer is on the scene

### ISSUE THREAD

**Issue by chelder86** [googlevr/gvr-unity-sdk#719]
The easier way to reproduce the issue is disabling the GvrReticlePointer Component of the GameObject with the same name in the GVRDemo scene. The raycast will stop working and the debug ray won't show.

GvrPointerPhysicsRaycaster should work without GvrReticlePointer, am I right?

**Comment by dsternfeld7** [comment]
This is intentional. GvrPointerPhysicsRaycaster and GvrPointerGraphicRaycaster shoot a raycast from a pointer (Anything that inherits from GvrBasePointer). If a pointer is disabled, then raycasting is disabled. GvrReticlePointer (cardboard reticle) and GvrControllerPointer (daydream controller) are the two pointer implementations that come with the SDK. 

If you desire to have Raycasting enabled with the reticle hidden, you can disable just the MeshRenderer component.

**Comment by chelder86** [comment]
@dsternfeld7 thanks for your clarification! :)
