### ISSUE TITLE
multiview feature for unity

### ISSUE THREAD

**Issue by wangxiaogangan** [googlevr/gvr-unity-sdk#720]
i am a developer from skybox mobile media player team, using unity's daydream sdk 

how long does the feature that single pass rendering already in android ndk will publish in unity?
is the multiview realized by unity's render loop?
## 
please tell me the approximate time for  multiview feature publish if prossible,  sorry to disturb you

**Comment by nathanmartz** [comment]
Single pass rendering is already enabled in Unity 5.6 for Daydream. However, due to a number of driver bugs, it is very rarely actually faster and we do not recommend developers enable it unless you are willing to spend time carefully profiling your app on different devices to ensure enabling single pass rendering is actually an optimization for you.
