### ISSUE TITLE
Instant Preview not working for GVR SDK 1.100 and Unity 2017.1

### ISSUE THREAD

**Issue by sanky369** [googlevr/gvr-unity-sdk#743]
I ran the GVR demo project which had the instance of Instant Preview and I connected my phone Axon 7 having the instant preview apk (updated one). Still, the preview didn't work in the phone like it used to do earlier for previous SDK versions.

**Comment by gstanlo** [comment]
We've noticed some issues with the latest version Instant Preview running on the Axon 7 phone. At this time the best suggestion we have is that a device update to the phone might help,. We're looking into this now, though.

**Comment by gstanlo** [comment]
Which version were you using before? Also, can you share your device and VR services version? For reference I've been able to get it to work with the following:

Model number: ZTE A2017U
Instant Preview: 1.0.0.57
Android: 7.0
vr services build: 1.10.170928015
MiFavor UI (?): 4.2

**Comment by CaptainScience** [comment]
I am also running into this problem.

Model number: ZTE A2017U (A2017UV1.1.0B32)
Android: 7.1.1
VR services: 1.10.170928015 (160729335)
MiFavor UI: 4.2
Unity: 2017.2.0f3

I had been using the Instant Preview 1.0.0.15 and SDK 1.70 which was working fine, but am now having trouble with it since trying SDK 1.100.1 (Instant Preview 1.0.0.65). I have also tried SDK 1.100.0 (Instant Preview 1.0.0.57), but that hasn't worked either. I have tried uninstalling Instant Preview from the phone, importing the SDK and Instant Preview into an empty Unity project, and running the GVRDemo scene but even 1.0.015 fails now. It will successfully install and run the app on the phone, but always fails to connect to the editor over USB.

**Comment by gstanlo** [comment]
Can you ensure that no other instances of Unity running Instant Preview are open? Also worth trying is to close all instances, run adb kill-server, and then reopen. It's rather puzzling that everything seems nearly identical (I tried updating to 7.1.1 as well). I can take a look at your logcat if you email it to me: stanlo@google.com.

**Comment by CaptainScience** [comment]
Got it working! I made sure to uninstall Instant Preview, kill all background apps, reboot the phone (just to be sure), and run "adb kill-server" when switching Instant Preview versions, and was able to get both 1.0.0.57 and 1.0.065 working. Thanks for the hint. Great to have that working again.

**Comment by kaminskypavel** [comment]
yup , uninstalling the "instant preview" apk , and restarting both the phone and the PC , did the trick here as well

**Comment by nathanmartz** [comment]
Looks like this is resolved. Hooray!
