### ISSUE TITLE
Laser out of sync with controller model

### ISSUE THREAD

**Issue by EvilBhalu** [googlevr/gvr-unity-sdk#747]
![1](https://user-images.githubusercontent.com/17793526/31509604-1c466acc-af50-11e7-89ed-7dd26dbf52d1.jpg)
![2](https://user-images.githubusercontent.com/17793526/31509606-1d162b22-af50-11e7-879e-463d2b805728.jpg)

Been trying to build an app with the latest GVR and Unity version 2017.1.1f1 but the laser is out of sync with the controller model. This causes some discrepancies during the movement and interaction since the laser points to the left of the controller, instead of being drawn forward. I tried to set the values through the Laser Pointer script but no luck. 
Any way to make sure that the laser is always pointing the same direction as the control, instead of being offset.

**Comment by dsternfeld7** [comment]
Can you post what the transform properties are on the object GvrControllerPointer->Laser ?

<img width="1078" alt="laser" src="https://user-images.githubusercontent.com/20076332/31510646-f0894ab4-af39-11e7-81a3-9cdf993d697b.png">

As you can see in the above photo, the position and orientation of the laser relative to the controller is determined by the properties on the transform. It is oriented 15 degrees downward so that it is ergonomically comfortable for user's to point, otherwise the user's may experience wrist strain when pointing at objects (especially when pointing downwards).

**Comment by EvilBhalu** [comment]
![3](https://user-images.githubusercontent.com/17793526/31520375-a6339d40-af73-11e7-8a43-56b211912ff5.jpg)

That seems to be the issue! My transform properties have been reset. Also, another thing I see is that your pivot point seems to be the front of the controller while mine is at the back.

**Comment by dsternfeld7** [comment]
Ya, the laser is positioned forward so that it is at the front of the controller.

If you reset the rotation to 0,0,0 then your app will not pass the "[Lower the laser ray an additional 15°](https://developers.google.com/vr/distribute/daydream/design-requirements)" design requirement and will be rejected from the play store. I strongly recommend that you keep the default values for the transform.

**Comment by dsternfeld7** [comment]
Based on your initial images, are you sure that the laser is actual offset to the left or does it simply look that way because of the perspective that you are observing the controller from? Have you observed the laser orientation on-device as well?

**Comment by EvilBhalu** [comment]
@dsternfeld7 I have. When using on-device (Pixel/S8) the issue pops up 4 times out of 10. It may not seem a high number but I'd rather not have the issue. 
Also, what values do you use for the Laser? My prefab values seem to be at 0,0,0 by default.

**Comment by dsternfeld7** [comment]
The default values in the prefab are in the image I posted above. If they are different for you, you may have applied changes to the prefab in the SDK.

**Comment by dsternfeld7** [comment]
Can you send an image of all settings you have set on GvrLaserVisual?

**Comment by EvilBhalu** [comment]
That's definitely a possibility. I've been messing with the settings so much, it's a possibility that I reset the values in the SDK. I'll pull a new version for the next project.

Attaching the settings on GvrLaserVisual -->

![5](https://user-images.githubusercontent.com/17793526/31521190-9dce654c-af76-11e7-9111-a76f87608056.jpg)

**Comment by dsternfeld7** [comment]
I don't see anything wrong in the inspector, if you can send me a simple project that re-produces the issue I'll take a look.

**Comment by EvilBhalu** [comment]
I think I'll build the project I'm working on and see if the issue pops up again. I think resetting the rotation to the original prefabs value and shifting the laser to the front of the pointer should solve the offset. 
I'll also build a new, simple project and see if the issue persists. Thank you for the transform values!

**Comment by dsternfeld7** [comment]
No problem!

Do you have any updates on this issue from your end? If not, I will close the issue.

Thanks,

Dan

**Comment by dsternfeld7** [comment]
Closing this issue. Please feel free to open a new issue on this topic if you need help with it in the future!

Thanks,

Dan

**Comment by EvilBhalu** [comment]
Hi,

There are no updates on this! The issue did not come in a new build. I think it was mostly due to changing the default values from the package. I'll repost if it arises again.

Thank you.
