### ISSUE TITLE
How to detect from which launcher app was laucned? From app list or from daydream launcher?

### ISSUE THREAD

**Issue by VadimTikhonyuk** [googlevr/gvr-unity-sdk#753]
Hi, there
My app have hybrid mode 2D + Daydream
This is what I want to do:
If user launch from app list - open 2D scene
If user launch from daydream - open VR scene

Anyway to do this?

**Comment by fredsa** [comment]
Sure:

Make sure **Player Settings > Android > Other Settings > Virtual Reality Supported** is checked.
Make sure **Player Settings > Android > Other Settings > Virtual Reality SDKs** lists:
1. **None**
1. **Daydream**.

This is ensures that:
* When launched from Daydream home, extra intent information is used to trigger use of the **Daydream** VR SDK. See `GvrIntent.IsLaunchedFromVr()` for an example of how the intent information is retrieved.
* When launched from the home 2D launched, the default/first **None** VR SDK is used.

To switch between modes at runtime, see https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime.

**Comment by VadimTikhonyuk** [comment]
@fredsa `GvrIntent.IsLaunchedFromVr()` return False everytime if None VR SDK on first place.
If Daydream then True
But If I launch from home 2d launcher, then I need to put phone in helmet to continue

I see only one solution, it's run in 2D mode, then I run VR to check for the presence of the start from the VR mode and then change the behavior accordingly

**Comment by VadimTikhonyuk** [comment]
So how to fix this?
If launch from home 2D - launch as 2D application without any daydream intros
If launch from daydream launcher - launch daydream sdk + VR scene

**Comment by fredsa** [comment]
You only need to set **Player Settings > Android > Other Settings > Virtual Reality SDKs** to [**None**, **Daydream**]. If you launch the app for the first time from Daydream home, it will launch in Daydream VR mode automatically. If you launch from the 2D launcher for the first time, it'll launch in 2D mode.

If you're testing one after the other, be sure to tap the recent apps button and swipe your app away so that the activity is killed. Otherwise the existing app (in whatever mode it was in) will simply reappear.
