### ISSUE TITLE
SDK wouldn't compile: Unity 2017.2.0f3 renamed UnityEngine.VR --> UnityEngine.XR

### ISSUE THREAD

**Issue by Rollo-Liu** [googlevr/gvr-unity-sdk#756]
For instance: 

> [Unity] Assets/GoogleVR/Scripts/Controller/ArmModel/GvrArmModel.cs(396,26): error CS0117: `UnityEngine.VR.InputTracking' does not contain a definition for `GetLocalRotation'

To fix those errors we need to replace all `UnityEngine.VR` to `UnityEngine.XR`.

**Comment by bopangzz** [comment]
Thanks for the report! We will get this fixed in our next release.

**Comment by rusmaxham** [comment]
Unity will auto-upgrade the code in the GVR SDK for Unity to UnityEngine.XR.  When you import the package into Unity, a dialog will appear:

<img width="562" alt="screen shot 2017-10-18 at 11 42 23 am" src="https://user-images.githubusercontent.com/13911074/31736383-6f61ccda-b3f9-11e7-9daa-f8f80034f7bd.png">

Click "I Made a Backup. Go Ahead!"

Because we support older version of Unity which use the older API name and Unity provides an automated process for upgrading the API for newer Unity versions, we will not be upgrading the API in our SDK at this time.

**Comment by Rollo-Liu** [comment]
@rusmaxham 
Thanks for your reply!

Unfortunately, your suggestion will not completely solve the issue because some of the references are not being used -- they have been flagged out by `#if UNITY_EDITOR`.

For example, in GvrArmModel.cs, line 404:
```
  protected Vector3 GetHeadPosition() {
#if UNITY_EDITOR
    return GvrEditorEmulator.HeadPosition;
#else
// This line will not get compiled in Editor mode so Unity will not automatically upgrade the API for you
    return InputTracking.GetLocalPosition(VRNode.Head); 
#endif // UNITY_EDITOR
  }
```

My suggestion is to flag out all `using UnityEngine.XR` with the compiler flag `#if UNITY_2017_2_OR_NEWER`. i.e.
```
#if UNITY_2017_2_OR_NEWER
using UnityEngine.XR
#else
using UnityEngine.VR
#endif
```

**Comment by rusmaxham** [comment]
Unity prompts me to upgrade those call sites at build time.  Does it not for you?

We are working on a proper fix to this issue as well.

**Comment by Rollo-Liu** [comment]
@rusmaxham 

No. I was using cloud build that's probably why it wouldn't fix it for me.

I have also tried a local build and it did prompt me for an API upgrade. That's a new trick for me -- thanks a lot 👍

**Comment by rusmaxham** [comment]
There is also a new Unity command-line argument in 2017.2: '-accept-apiupdate' which will accept the API upgrades when run in headless mode.

**Comment by fredsa** [comment]
The 1.110.0 release includes this relevent:

> Auto API updater no longer needed to update `UnityEngine.VR` to `UnityEngine.XR` when using Unity 2017.2 or later.

**Comment by Rollo-Liu** [comment]
Thank you! 👍
