### ISSUE TITLE
GvrAudioSource emits no sound in build without GvrAudioRoom

### ISSUE THREAD

**Issue by jhclaura** [googlevr/gvr-unity-sdk#768]
Without GvrAudioRoom, there's no sound from GvrAudioSource in build app.
There's sound in Editor play mode, but not in build.
Is it a requirement to use GvrAudioRoom now? Any guidance appreciated!

Found using:
 * Google VR SDK version: v1.100.1
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version:  iPhone 6s, iOS 11.1

Steps to reproduce the issue:
 1. open demo scene GVRDemo
 2. disable GvrAudioRoom under cubeRoom
 3. build app to hear no sound

**Comment by anokta** [comment]
Hi,

The GvrAudioRoom component is optional, GvrAudioSources do not require adding a room to play sounds.

I believe this is indirectly caused by #665, and can verify that updating the GVR iOS CocoaPod to v1.100.1 worked for me. Please see the issue #665 and the corresponding iOS guide [here](https://developers.google.com/vr/ios/get-started) for further information.

**Comment by jhclaura** [comment]
Thank you for the reply and links @anokta !
Verified that after `pod update` within the generated Xcode folder, the issue resolved. Yea!
