### ISSUE TITLE
thermal limit daydream bug?

### ISSUE THREAD

**Issue by sterlingcrispin** [googlevr/gvr-unity-sdk#779]
I overheated my pixel lastnight after 40+ minutes stress testing my app, then left my phone unplugged overnight, and this morning was getting really subpar performance. I assumed the battery was too low and charged it to 70% yet the issue didn't go away until I rebooted the device.

My guess is that the thermal throttling logic set some kind of platform level flag in daydream and that flag didn't properly clear itself when the phone cooled off. Has anyone else seen this issue?

On a related note: is there a way to detect the kind of screen-tearing that can occur when the performance is throttled? My app is already checking for FPS and adapting to that but I'm not sure that measuring the milliseconds since last frame is an accurate way of detecting any screen-tearing artifacts. I'd like my app to adapt to this circumstance if possible and try to avoid it.

Found using:
 * Google VR SDK version: v1.110.0
 * Unity version: 5.6.1.f1
 * Phone manufacturer, model, and O/S version: google pixel 1st gen
 * Viewer manufacturer & model: daydream 1st and 2nd gen

**Comment by jdduke** [comment]
@sterlingcrispin: Did you observe a warning notification when you reached the thermal throttling threshold? If you exceeded the threshold, you should have been taken to a scene prompting you to remove the phone from the headset. This is not really a situation that apps can handle very gracefully, which is why we have the automatic behavior. what version of Google VR Services did you have on the device?

The device will remain thermally throttled as long as it remains in VR mode, but it should become unthrottled after leaving VR mode (provided the temps are now under the usual limits). If you're seeing otherwise, a bug report would be helpful. Thanks.

**Comment by sterlingcrispin** [comment]
@jdduke yeah I received the standard warning and ceremoniously took the headset off but it remained throttled for 12+ hrs until I rebooted the device.  Daydream VR settings reports build version 1.10.172754103 not sure if thats VR services or not

Happy to provide a bug report just let me know where to send it

**Comment by jdduke** [comment]
Per offline discussion, we weren't able to determine if this was thermal-related, and there weren't any other red flags in the bug report. Please re-open if you hit this again. Cheers.

**Comment by sterlingcrispin** [comment]
hey @jdduke actually this happened to me again two days ago on the latest android version , its really evident on my app Cyber Paint on the daydream store because it does a lot of heavy graphics calls so when its throttled you can visibly see screen tearing due to missed vsync calls and whatnot. It remains that way until charging the device and then rebooting it, where I'd expect charging it would be enough and rebooting wouldn't be necessary.

**Comment by jdduke** [comment]
@sterlingcrispin: Have you tried enabling sustained performance mode for your app? There are some [instructions here, "under the Targeting Daydream (Android only)" section](https://docs.unity3d.com/Manual/VRDevices-GoogleVR.html) on how to configure this within Unity.
