### ISSUE TITLE
VR camera always start from a fixed position

### ISSUE THREAD

**Issue by linglonglinglong** [googlevr/gvr-unity-sdk#785]
When I press the play button, no matter where I place my camera, with the GvrEditorEmulator, the camera always start from the same position! I put it as a child of my camera. I want it to move with my camera. But it stops my camera from moving and it's at the same place. In the online tutorials, people with previous versions of GVR SDK can do it!

Found using:
 * Google VR SDK version: 1.100.1
 * Unity version: 2017.1.0f3
 * Phone manufacturer, model, and O/S version: not even tested on phone
 * Viewer manufacturer & model: ___

Steps to reproduce the issue:
 1. have a camera that always move in the forward direction
2. Drag GvrEditorEmulator in the scene.

Workarounds:
___

Additional comments:
___

**Comment by dsternfeld7** [comment]
To solve this, do the following:

1. Create a GameObject named 'Player'.
2. Move your camera underneath the 'Player' object and set it's position to (0,0,0).
3. Position the 'Player' object to where you would like the camera to be.

GvrEditorEmulator will override the position of the camera to emulate the [Daydream Neck Model](https://developers.google.com/vr/distribute/daydream/design-requirements#UX-D8) which offsets the position of the camera based on the camera's orientation so that the camera pivots around an approximated neck instead of the center of the eyes.

Also, GvrEditorEmulator does not need to be a child of your camera. It automatically controls the pose of all stereoscopic cameras in the scene regardless of where it is located in the scene hierarchy.

**Comment by rusmaxham** [comment]
I assume this has fixed your issue.  If not, please reopen this issue.

**Comment by linglonglinglong** [comment]
This solves the problem!

**Comment by bapps16** [comment]
Same here, problem solved, thank you so much!

**Comment by krose1980** [comment]
I can confirm (my frustration level is over the moon) that camera drops only in emulator mode, it's good and stays in position when running built version (eg on phone). God I wasted so much time :)
