### ISSUE TITLE
Strange 2D mostly black screen on permissions flow

### ISSUE THREAD

**Issue by sterlingcrispin** [googlevr/gvr-unity-sdk#798]
Not sure when this started happening but my app is displaying this strange 2D (presumably android) screen right before the standard "remove your device from the headset" prompt that daydream provides.

![screenshot_20171129-152838](https://user-images.githubusercontent.com/2976761/33403708-a89e889e-d51e-11e7-9136-f90f2e4b72f1.png)

Has anyone seen this before ? What is this?

I'm using the permissions flow demo code and the Google provided android manifest that mentions the 6DOF comment 

Found using:
 * Google VR SDK version: 1.100.1
 * Unity version: 5.6.1.f1
 * Phone manufacturer, model, and O/S version:  Google Pixel
 * Viewer manufacturer & model:

**Comment by chaosemer** [comment]
Can you check if you can reproduce this issue with the 1.110 release? I made a fix for this that got into 1.110 and I'm very curious if I missed a case.

**Comment by sterlingcrispin** [comment]
@chaosemer hey that did it! I hadn't noticed a new version had come out or read it's release notes to know

why was that happening at all anyhow? I'm curious what the underlying issue was

**Comment by chaosemer** [comment]
Happy to explain! Warning, some gory details follow.

Being in VR mode is a feature tied to Android activities. Switching out of VR (to pop up the permissions request) requires switching activities. The screen you see with the app's name in a box is what the permission activity used to look like.

Now it wasn't always that way, we recently inadvertently changed the permission activity to have the "Dialog" theme. The Dialog theme fell had default content: the App's name as title, no body, and no dialog buttons.  So in other words, the app's name in a box. The fix was very easy, to remove the Dialog theme, and have a completely empty UI.

And now you know!
