### ISSUE TITLE
Gvr Video Player Texture does not work with Single Pass Rendering 

### ISSUE THREAD

**Issue by wangvnn** [googlevr/gvr-unity-sdk#816]
When single pass rendering is enabled, GVRVideoPlayerTexture doesn't work.
When attempting to show it, logcat shows the below error:

E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state

Found using:

Google VR SDK version: v1.110.0
Unity version: 2017.3.0
Phone manufacturer, model, and O/S version: Pixel XL Android 8.1.0
Viewer manufacturer & model: Daydream View (2017 or first one)

Workaround: Disable Single Pass Rendering

**Comment by morganpage** [comment]
Thanks for this, I'd already wasted some time trying to work out why my videos were suddenly not playing but you saved me wasting any more time, most grateful!

**Comment by fredsa** [comment]
Single Pass (multi-view) support is currently in "Preview" and should probably not been used in production apps due to devices with bad drivers that fail to render content correctly.

Unity has recently added a warning about this. Here's a screenshot from Unity 2017.3.0p1:

<img width="466" alt="multi-pass-warning" src="https://user-images.githubusercontent.com/1235362/34633114-be6e992a-f22e-11e7-903d-ac231967838a.png">

Please use "Multi Pass" rendering for now.

**Comment by fredsa** [comment]
Filed issue #828 to track the feature request.

**Comment by rusmaxham** [comment]
[This patch of VideoUnlitShader.shader](https://gist.github.com/grendell/0d3d53f004aba8ef576b54690d98e3d2/91d355643a2abb6632efc946402e9009b1a7be0f) enables GvrVideoPlayerTexture to work with the single-pass rendering path method on 2018.3.14 and later.
