### ISSUE TITLE
VideoDemo Scene doesn't work even with GVRVideoPlayer.unitypackage imported

### ISSUE THREAD

**Issue by LightOwlFlies** [googlevr/gvr-unity-sdk#830]
VideoDemo Scene doesn't work

Found using:
 * Google VR SDK version: GoogleVRForUnity_1.110.0___
 * Unity version: 2017.2 1f1 ___
 * Phone manufacturer, model, and O/S version: N/A get the error in Unity
 * Viewer manufacturer & model: N/A get the error in Unity___

Steps to reproduce the issue:
 1. In Unity Import Package GoogleVRForUnity
 2. In Unity Project tab open GoogleVR folder and click on GVRVideoPlayer.   Assets are imported.
3. Press play and get the error message "Please add the GVRVideoPlayer.unitypackage to this project"  
In the console the error message is "Not implemented on the platform Unityengine.Debug:Log(Object)"

 
Workarounds:
___none that I know of

Additional comments:
I did not modify anything - I just want to see the demo but it doesn't work._

When I click on GVRVideoPlayer.unitypackage again it tells me that there is nothing to import because the package is already in the project

![gvrerror](https://user-images.githubusercontent.com/8193436/34895115-1e15e1a2-f799-11e7-9560-3948d639f807.JPG)

**Comment by LightOwlFlies** [comment]
doesn't  work in editor

**Comment by ylluminarious** [comment]
Not sure why you closed this issue @LightOwlFlies. I cannot even get video to work in Daydream, let alone the editor. Plus there are some other gaping anomalies which indicate that this is still a real issue. Also, I'm writing this comment on the most recent SDK version, `v1.120.0`.

The root of this problem seems to be that `GetRenderEventFunc` is *only* defined as:

```csharp
  private static IntPtr GetRenderEventFunc() {
    Debug.Log(NOT_IMPLEMENTED_MSG);
    return IntPtr.Zero;
  }
```

Although it seems that it is supposed to be defined differently based on the platform. Because otherwise it will ***always*** block `IssuePlayerEvent` which is called by `Init` which is used to play video:

```csharp
  private void IssuePlayerEvent(RenderCommand evt) {
    if (renderEventFunction == IntPtr.Zero) {
      /* it looks like GetRenderEventFunc is supposed to do something here
       * but it can only ever just log "Not implemented on this platform" */
      renderEventFunction = GetRenderEventFunc();
    }

    if (renderEventFunction == IntPtr.Zero || evt == RenderCommand.None) {
      Debug.LogError("Attempt to IssuePlayerEvent before renderEventFunction ready.");
      return;
    }

    GL.IssuePluginEvent(renderEventFunction, videoPlayerEventBase + (int)evt);
  }
```

I am really not sure how exactly this is supposed to work. But this broken chain of logic alone seems to make video a no-go in Daydream. If I'm missing something, I would definitely appreciate some help here. This honestly seems like it's a bug.
