### ISSUE TITLE
Updating Podspecs for 1.130.1

### ISSUE THREAD

**Issue by alimoeeny** [googlevr/gvr-unity-sdk#880]
I went ahead and created a PR: https://github.com/CocoaPods/Specs/pull/14372
What it lacks is direct download link to dl.google.com

**Comment by alimoeeny** [comment]
@rusmaxham follow up from the discussion under https://github.com/CocoaPods/Specs/pull/14372
I just copied over the exiting podspec. 
It looks like, and makes sense, the way to go is to add the podspec to this repo, not to update cocoapods specs directly. 

I don't know what your policy is, can I make a PR to this repo with the podspec.

And to answer your question, since unity itself does not keep up with the changes in this repo, we manually update our Podfile pointing to this repo.

**Comment by rusmaxham** [comment]
Yeah, the CocoaPods are for entirely native iOS code, not Unity plugins.  The Unity plugin doesn't come with a podspec and I don't believe there is a way to override the Unity built-in.  Unity has a copy of the entire GVR iOS CocoaPod embedded in it so that iOS Unity developers don't need to have CocoaPods installed in order to build for iOS.  AFAIK, there is no way for us to override that in our plugin.

**Comment by alimoeeny** [comment]
@rusmaxham I am not sure if I understand what "entirely native iOS code" is.
We have project, which can be called a "plugin", in which it is generated by doing a Unity build and we use cocoapods to add many packages including GVR to it, which I believe overrides Unity's embedded GVR.
We have been upgrading out GVR independent of Unity's slow upgrades. 

My questions are,
1- do you mind including a .podspecs file in your repo? 
2- where can I get the link to the latest binary distribution from dl.google.com like: https://dl.google.com/dl/cpdc/2d6b597cb1a13b1c/GVRSDK-1.120.0.tar.gz but for 1.130.1 ?

Thank you,

**Comment by rusmaxham** [comment]
I'm not sure that this is even possible.  Unity has a copy of the GVR CocoaPod embedded in it that it copies into Cardboard iOS builds so that developers don't need to have CocoaPods installed.  Adding a podspec to the GVR SDK for Unity won't change what version of the pod ends up in iOS.  Developers will need to have CocoaPods installed on their system and then run `pod update` after Unity generates the Xcode project to get an updated version of the GVR CocoaPod, and this process doesn't need an updated spec, as the podfile included in Unity specifies version or newer, allowing newer versions to be installed on `pod update`.

**Comment by alimoeeny** [comment]
That is exactly what we do. 
Unity build is the first step of our build system, then we have some custom scripts that we run which includes `pod install` or `pod update` (depending on some other conditions) and then an xcode build. 
For that purpose, we would appreciate an up to date podspec file.
Of course we can alternatively just point to the repo on github, but it would be cleaner to have proper pod and podspecs set up.

**Comment by rusmaxham** [comment]
Does the `pod update` step not get you the latest iOS CocoaPod?  It should.  The latest is still 1.120, tho.  There was no 1.130 release for iOS this cycle.

**Comment by alimoeeny** [comment]
It does, 
it gets up 1.120
I thought the latest version is 1.130.1 based on: https://github.com/googlevr/gvr-unity-sdk/releases/tag/v1.130.1
What am I missing?
Sorry I am dragging this conversation, and I appreciate your responses

**Comment by rusmaxham** [comment]
Ah good, `pod update` is working.

There are separate releases for the platform SDKs ([Android](https://github.com/googlevr/gvr-android-sdk/releases) and [iOS](https://cocoapods.org/pods/GVRSDK)) and the engine SDKs ([Unity](https://github.com/googlevr/gvr-unity-sdk/releases) and [Unreal](https://github.com/googlevr-unreal/UnrealEngine/releases)).  Usually platform SDKs both release in sync, but this cycle iOS was skipped for reasons.  Engine SDK releases usually trail by a couple of weeks.  Unreal is lagging Unity a bit this cycle for reasons.
