### ISSUE TITLE
Can you see the split-screen view in the editor?

### ISSUE THREAD

**Issue by bsabiston** [googlevr/gvr-unity-sdk#892]
All the online tutorials show Unity with the VR stereoscopic view emulated in the Unity Game View window.  How do you do that?  Can you only view the split screen view on an actual device now?  Does that mean that every time you want to test it you have to go through the whole build and run phase???

**Comment by vinhui** [comment]
The GoogleVR package comes with [Instant Preview](https://developers.google.com/vr/develop/unity/instant-preview)

**Comment by bsabiston** [comment]
Isn't that Android only?  I'm on iPhone...

**Comment by fredsa** [comment]
Since it's not possible to hold the viewer up to your development machine's display to see correct stereo image and depth in any kind of preview image, there isn't all that much benefit to having a stereo preview view in the editor.

You can however develop your app in the Unity editor without having to build and install the app on every iteration. In fact, it's generally easier to work in the editor with a monoscopic view, and then separately test out stereo / depth on a real device on headset when you really need to view the scene in VR.

You're options include:
- On Android there's Instant Preview as @vinhui mentioned above, which lets you stream a stereo view from Instant Preview in the editor to your phone over USB or Wi-Fi; changes you make in the editor affect the experience on the device in real time
- If you have access to a supported desktop headset such as an HTC Vive, you can do a lot of quick iteration in the editor, so save yourself build/iteration time

If there's some reason that you really want to see stereo preview image inside the editor game view, you can switch the build platform to Android and add the **Mock HMD - Vive** VR device, which works in the editor. You'll get a stereo view, but without the lens distortion.

**Comment by fredsa** [comment]
Understood. You might be able to look at some of the really old rendering code (i.e. pre-1.0 SDKs), back when there wasn't any native integration. Those older SDKs had Cardboard profile based distortion rendering in the editor.

Note, however, that the lens distortion and field of view can vary quite a lot from viewer to viewer. The user's IPD can also affect which parts of the visual field they can actually see. All in all, working near the edge of the field of view is problematic unless you know beforehand which viewers will be used, and account for user-to-user variance.
