### ISSUE TITLE
Motion Blur

### ISSUE THREAD

**Issue by dvnelson72** [googlevr/gvr-unity-sdk#907]
Summary:
I have an Oculus / Vive / Gear VR application.  Gear VR looks perfect on my Galaxy S6.

However, when I build for Cardboard, I get a motion blur that is distracting and makes the application feel laggy.

So, I built an apk for with the HelloVR scene in the unity package.  I have the same problem.  I added some console logging and the app is getting 59.3 FPS.

I did one build for iOS.  On an iPhone X, I have the same problem.  

It appears to be part of the rendering pipeline.  But I haven't added anything to the demo scene.

Found using:
 * Google VR SDK version: 1.130.1
 * Unity version: 2018.1.0f2
 * Phone manufacturer, model, and O/S version:  Samsung Galaxy S6
 * Viewer manufacturer & model: Google Cardboard

Steps to reproduce the issue:
 1. Build apk with HelloVR as the only scene
 2. Start the app
 3. Twist your head left and right and concentrate on the target thing.

**Comment by rusmaxham** [comment]
GearVR and Daydream devices are able to put their screens into a low-persistence mode which eliminates the blur and other low-level platform integration features allow the lag to be reduced.  Unfortunately, this is not possible on iOS devices, non-Daydream, and non-GearVR devices due to the lack of operating system and hardware support for these features.
