### ISSUE TITLE
Camera FOV (Field of View) not changeable at all

### ISSUE THREAD

**Issue by zenhund74** [googlevr/gvr-unity-sdk#938]
Summary:
Sine the native integration of VR SDks in Unity, the Camera FOV settings doesn't effect the build at all.

In the Unity documentation under [https://docs.unity3d.com/Manual/VROverview.html#UnderstandingTheCamera](https://docs.unity3d.com/Manual/VROverview.html#UnderstandingTheCamera) it says:

Each Camera that is rendering to the device automatically replaces the FOV of the Camera with the FOV that the user input in the software settings for each VR SDK. The user cannot change the field of view during runtime, because this behaviour is known to induce motion sickness.

That I find totally acceptable, as changing the fov during runtime, can surely cause optical irritation.

But I didn't find any software settings for setting a fixed FOV for all VR Cameras, which would bring me a lot further building my app right.

Therefore I find this behavior of the software far to restrictive, because I have a good reason changing my overall FOV of the cameras, to show panoramic pictures perfectly sized on my screen.

Is there any possibility to change the basic FOV settings for the SDK integration? The known workarounds like creating a parent object and scaling doesn't work for me, as I have a rotating zylinder with the panorama picture. Scaling the zylinder or the player has no effect at all, as scaling three dimensional objects also means scaling the texture.

So changing the FOV is my only option.

Kind regards, zenhund 74.

Found using:
 * Google VR SDK version: any since native integration
 * Unity version: 5.6.5f1
 * Phone manufacturer, model, and O/S version: HTC M9 Plus, Android 5.2
 * Viewer manufacturer & model: ----

Steps to reproduce the issue:
  
Workarounds:

No workarounds found yet, scaling, even the neck offset, to get the camera closer to the texture in the zylinder doesn't work. Also changes in the GVREditorEmulator are ignored totally, as this script is meant to be an editor emulation only and is not compiled into the build.

**Comment by rusmaxham** [comment]
As stated in the Unity documentation, all VR rendering systems have a fixed FOV.  Works as intended.  Related to [issue 937](https://github.com/googlevr/gvr-unity-sdk/issues/937)

**Comment by fredsa** [comment]
@zenhund74 To clarify, the reason that Unity does not allow you to set the camera FOV while in VR mode is that **the FOV of the virtual camera _must_ match the physical FOV of the optics inside the currently connected VR headset**.

If these FOV of the virtual camera and the FOV of the headset's optics are not the same, then the virtual scene will render incorrectly and the world will appear to rotate incorrectly when the user turns their head. This leads to user discomfort and motion sickness.

—

It sounds like the effect you're trying to achieve in your app is to "zoom in" or "zoom out", so that the rendered VR scene is at the desired size & scale.
- If you were building a (non-VR) flat / 2D app, then you could use camera FOV to achieve this effect.
- To achieve the same "zoom in/out" effect in VR, it's not possible to use camera FOV and have the experience be comfortable for your users. You can however set the scale of the transform for a game object that is a parent to the camera (as I described in issue #937). This will cause the world and everything in it to grow or shrink.
