### ISSUE TITLE
Manually setting GvrPointerInputModule.Pointer

### ISSUE THREAD

**Issue by vinhui** [googlevr/gvr-unity-sdk#944]
When you manually set the `GvrPointerInputModule.Pointer`, the `GvrPointerGraphicRaycaster` doesn't clear the `cachedPointerEventCamera` field. Adding 
``` csharp
if (cachedPointerEventCamera != null &&
    cachedPointerEventCamera.gameObject != GvrPointerInputModule.Pointer.PointerTransform.gameObject)
{
    cachedPointerEventCamera = null;
}
```
between line [175](https://github.com/googlevr/gvr-unity-sdk/blob/master/Assets/GoogleVR/Scripts/EventSystem/GvrPointerGraphicRaycaster.cs#L175) and 176 in `GvrPointerGraphicRaycaster` will fix this issue.

Found using Gvr v1.150.0

**Comment by rusmaxham** [comment]
Good catch.  We'll look into this.

**Comment by thesambassador** [comment]
This issue gave me some MAJOR headaches during one of my projects. In my instance, I had different objects for left/right hand pointers and was setting one of them inactive and setting the pointer, but when the pointer changes it doesn't correct the cachedPointerEventCamera.  So the existing GraphicRaycasters will be completely off when raycasting.  The above line is fine as a workaround but it'd be nice to have an official fix so that I don't have to worry about upgrading GoogleVR versions.

**Comment by rusmaxham** [comment]
This will be fixed in the next release.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
