### ISSUE TITLE
BLE issue when using SDK in Unity

### ISSUE THREAD

**Issue by skywolf829** [googlevr/gvr-unity-sdk#955]
This is an issue I opened up some time ago that still is not resolved. A reply happened on the issue thread, but I was at SIGGRAPH and didn't respond quick enough, sorry about that.

After adding GoogleVR SDK to a Unity project with functioning BLE capabilities, BLE no longer works.

Found using:

Google VR SDK version: v1.150.0
Unity version: 2018.2.5f1
Phone manufacturer, model, and O/S version: Google Pixel 2, 9.0
Other hardware: Arduino Uno + HM-10 BLE master-slave module coded to connect via BLE

Steps to reproduce the issue:
1. Create empty Unity project, add minimal code to incorporate BLE connectivity (using Asset store plugin Bluetooth LE for iOS, tvOS, and Android by Shatalmic Inc).
2. Build to phone and run, verify that it connects to the HM-10 sensor on my Arduino Uno.
3, Uninstall app from phone.
4, Enable Virtual Reality support in Unity XR settings for Android.
5, Build to phone, verify it still works.
6, Uninstall app from phone.
7, Import GoogleVR SDK unitypackage. Add "Cardboard" to list of supported VR platforms in XR settings.
8, Build to phone, observe that BLE no longer connects.

I've also used Unity's export option to change the android manifest in Android Studio and run from there. I changed `<meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />` to be false. This forces accepting of permissions when the app starts, but the app still doesn't connect to the BLE sensor.

I've been in contact with the creator of the plugin, and he doesn't quite know where to go either.

What I've been able to trace is that once my BLE script is started, instantiates a BLE scanner, and goes in a "scan" state, it doesn't actually identify any potential connections around it, as it does before importing GoogleVR. It's as if the bluetooth scanning is being blocked by something inside of the GoogleVR package.

**Comment by skywolf829** [comment]
I disabled Google VR services and it worked properly!

Currently, we aren't developing for Daydream, and we don't own one to test on. We are planning on making the app daydream compatible, though. 
I think I'll be purchasing a Daydream soon - I can update this thread with the result of that test.

**Comment by rusmaxham** [comment]
Please do keep us posted on the results of your findings.

**Comment by skywolf829** [comment]
Just got to test with a Daydream 1. The device's Bluetooth still seems to be "blocked" after connecting with the Daydream controller. My script continues to search for bluetooth devices but none are ever returned.

I verified that when I disable Google VR services on the phone, my app correctly connects with my Arduino.

Any idea what's going on?

**Comment by skywolf829** [comment]
Following up - any ideas?

**Comment by sigmaxipi** [comment]
It's unclear what the issue is. When I try using [Chrome's Web BT samples](https://googlechrome.github.io/samples/web-bluetooth/device-info-async-await.html) while in split-screen mode with a DD app, the DD app gets controller information and Chrome can find other BLE devices. One way to debug this may be to use the [sdk-controllerclient](https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-controllerclient) sample which is a 2D app that uses the Daydream API to talk to a server.


If adding BLE scanning to that sample works and it can detect other BLE devices while it's paired with a controller, then the issue is with the Unity plugin. If the modified sample can't detect other BLE devices, then the issue is with DD blocking BLE scanning.

**Comment by lhargrove** [comment]
I also have this issue. Did anyone ever get a functioning solution?
